#+title: A Miraculous Find
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="index.css" />

Plans for the next morning, included: Wander around in the woods with Gog. Gog and Grav were cousins. Pretty much the same age, much-little.

Grav and Gog had been same-cousins[fn:: First cousins] and highest-friends for their whole lives. They'd been living together in Bhorv Zolk for about half of that time, off and on throughout their lives.

They had the same instinct for benefit-crazy-think, a term that means, "To benefit from free and open thinking and doing." In other words, to experiment. Importantly, this was a word of /theirs/. The Crec almost universally would never buy the "benefit" part.

Both realized, through their endless talking about ideas, that if you explore the idea places that no one else will because they are lazy or superstitious, you will more easily find value-stones[fn:: This just means 'gem', but the literal meaning of the constituent words and their order is exactly what the Crec say. The concept of 'value' is one of Grav's obsessions. He therefore is one of relatively few who ever stopped, once in their life, to decompose this particular word and realize, like you have done at least once: /Oh neat. it's X + Y. I've been using this word my whole life and I only just now realized!/] of ideas that, because they were original, unexplored, and sometimes striking in their unusualness, were more profitable than average.

Grav and Gog were no longer children. Their minds had sort of overlapped, after years of complex communication. There was nothing supernatural or exceptional about this. It happens all the time, and they were just a slightly higher-functioning example. They, together, had some pretty amazing ideas. Some would call this relationship a "friendship".

Grav and Gog /were/ friends. They were also accomplished gentleman philosophers. The advantage they could have had over people was immense, but they used their powers for good. They wanted to have fun and wanted for everyone else to have fun. Like many good people, they saw a spoil-sport as a kind of project for them to undertake; someone who needed some loosening up, or possibly someone who just needed to have a good cry, which they were always willing and able to help bring forth, with purity of heart.

Not everyone was of this mind. Verk was staying in the burrow just two down from Grav, and inevitably they would run into each other. Often this was in the relief-burrow, as had happened the night before.

The relief-burrow was positioned and shaped for optimal sound-deadening, for reasons that would utterly relate to modern readers. It was shaped, looking top-down, something like a daisy; scalloped around the perimeter so that sound would naturally dampen. The walls were also gently bowed outward from top-to-bottom. It offered the predictable visibility and viewability characteristics of a large, circular room, but didn't have the /acoustical/ characteristics of a large, circular room. Get it?

There was a constant, rather soothing, gurgle and plash of water. Although minimal and somewhat termpermental, the cave system had a small number of spring-fed water works. The relief-burrow was by a wide margin the biggest consumer of water. The Crav thought it all pretty clever and eminently maintainable: The circular room had a slight, very inconspicuously conical floor that was highest at the center and had a "one thing down for each one half of one boulder-door thing over[fn:: 1:50]" grade; enough to keep the entire room's floor (8 man diameter) covered in a sheet of two bowstring-finger-knuckle deep, rapidly moving water[fn:: Astonishing fact: After the decline and fall of the Crec and surrounding culture, the next time a similarly-shaped water feature appeared on earth it would be called "The Super Slippery Fun Lagoon", appearing in a New Jersey water park called 'Garden State Water World' in 1934. nb: too goddamn silly.] from the center, where an immense gurgling pot of cold water overflowed continuously.

This was enough to create two small semiciruclar rivers from the entrance side of the room, around each half-circle of gutter, to the opposite side, closest to the hill's exterior, for the whole circular gutter was slightly tilted in this way. Once the water met the far side of the room (Where Grav noticed some mesmerizing patterns made by the two "rivers" colliding head-on.), it finally exited the room through a few arm-sized holes heading down what everyone always though of as "the back of the mountain".

This arrangement both took all your business briskly away, but it also thoroughly washed your feet, which were likely to be entirely black upon entering. Most Crec made it past the center of the room on their way out to wash their hands, always nearest the center.

In addition to this, there was a snaking entranceway into the relief-burrow that had two intentional characteristics: As the other end of this passage was facing the opening of the cave system to receive the most sunlight this would make the relief-cave more well-lit (as the walls, floor and ceiling of this passage were polished) but it would also catch the eye when someone was making their way into the burrow. It also had a couple of switchbacks, so the passage could be made longer and prevent a direct view into the burrow, for the Crec were not shy about pooping together, but they did think of the relief-burrow as unclean; a kind of topic and thing that should be kept hidden, but without overdoing it.

Yes, carving out an enormous room did take years. It would take a single person several lifetimes. But there were many hands to help and enough demand to make it a "not-think-thought". It took centuries of struggle and countless lives for the Crec and surrounding Forest to brute-force this kind of sophistication. It was a matter of survival. In a way, all of this was driven by the love of children. A humble Crec of note once remarked, "If we have gone further than others, it is because we are standing on a pile of bodies."

The Crec had the kind of sophistication and coordination abilities that you might find in a rather-out-of-the-way, mid-sized bronze age settlement thousands of kilometers from Babylon. The Crec Forest may have indeed been just that exactly. They would not be able to offer much more than speculation themselves. It's plausible. Either way, these things vary over distance as well as time. They were just doing them, and were not /all/ morons. There's a whole bunch you don't know about the "archeological record".

/A/ point to all of this is that the relief-burrow, given the right level of vigilance, could be thought of as reasonably suited for private conversations.

And as the day before, Verk and Grav found themselves in such a "conversation" this morning. But this time, there were no ears to witness. Both men were noted early-risers. And both men were practiced at judiciously using the relief-borrow for "clay-talk".

Verk had, what for Grav was a very unsettling characteristic as a person: He was a complete prolapsed-bison-rectum whenever he and Grav talked in truly private circumstances. He would be a slapper of shoulders and grinner of grins in more-or-less public circumstances. He seemed to be spending his life pretending to run for Elders-Quarum. As for his public behavior, something very close to that would be the only reasonable assumption for a neutral observer: /This person appears to be trying to sell his persona actively to people for some gain/, a very articulate and objective caveperson would say. And if he just shuts that off completely and becomes a different, increasingly nasty person in his presence... Grav was just not quite sure what to do with that.

Verk automatically smiled broadly at Grav as he walked into the otherwise empty relief-burrow to see Grav urinating with his back to the entrance. Grav therefore did not see this smile, though he knew someone was there.

"Grav, what is the good grunt?!", Verk said sharply, causing Grav's head to jerk around a bit too far.

"Good morning Father-Brother Verk. Father-Brother Verk, I was genuinely taken aback by our words from yesterday. I /do/ feel the way you do about our Forest. I know...about all that stuff. trust me. I will /never/ forget. My feelings /also/ are quite strong.

What have I done? Please, believe me; my conscience is free and I want to learn from you."

"Your conscience is free, huh? No, I want you to think on it. That's what you need. Verk stared with noticible anger still. Nice of you to at least notice I'm put-out with you. Your lot forgotten a lot more than you think you know.

While trying to decipher that, Grav was sure at least some kind of helpful hint was to follow this. It seemed to break the very rules of caveperson communication to just leave things hanging like this. He raised his eyebrows in a careful effort to relay this observation, gave up, closed his eyes and did his best at a 'reset', so he could think.

It often seemed that Verk could make it harder for him to do this, as if he had some /power/ that made you instinctively 'squirm' in a mental sense, as opposed to 'gather your thoughts and give a meaningful, honest response'. /It was as much Verk himself as it was that people had allowed Verk to/ become /this way/, Grav guessed.

"Yes, Father-Brother Verk. I will. Please forgive me. It is a large stone you put upon me. As you say, I will likely learn more if I do some discovery myself. That way I will remember stronger, as it is surely a grave misstep."

Verk made a hissing sound that Grav couldn't categorize for meaning, as he could not comfortably turn to look at Verk.

"What are you doing today?", asked Verk, still not /using/ the relief-burrow, but now standing where Grav could comfortably look at him. Now facial expressions could be used to hopefully glean more meaning from inscrutable Verk.

"Oh!" Grav was both excited to share some news and thankful for the change of topic. "Father-Brother Verk, Gog and I..."

Verk hissed again but Grav now could see that he was huffing with contempt, with an oddly abbreviated roll of the eyes.

"Gog, huh? You two copulating-monkey boys going deep into the woods today?", Verk made a complex dance of facial expressions and other gestures that Grav could not decipher, other than to note that maybe there was now glee. "Stay away from the bachelor-tree, you two." Verk made a sour, disdainful face. Grav thought that he could interpret this as an invitation to "yuck it up" with another man using banana-humor. He knew well that that was not the case here. So he responded with indignancy, as he knew he should.

"Father-Brother Verk! I would never! Please, there could be a quiet-one nearing in the entrance."

"We both know there is not.", Verk said with his arms crossed.

"What are you and Gog up to? Hopefully something constructive."

"Yes, I think so, Father-brother Verk. We are going to find more value-stone where we have been for several moons. We have quite an infrastructure there. We think there is a vein of them following the river, but we didn't have time to look around much last time."

"Get some strenuous work in while you're at it. If you bring me a value-stone agreed by all to be worth three deer carcass I will let you out of this upcoming club-drill. You probably want to frolic in the woods."

"Father-Brother Verk, I will do /both/! I will bring you such a stone and I will excel at the next club-drill with the spirit of the Forest strong in me!"

"Yeah." is all Verk said.

He turned on his heels and said to Grav while leaving, "Keep your entails on the inside."

The click of his hyena spurs[fn:: These are raptor talon that are strung by sinew so that they point backwards and downwards from the heel, with just one talon per foot, but they are large and serve their function. They are fastened strongly, but often with just enough slack so that the talon makes an audible "click" while the wearer walks around in-cave.] faded down the entranceway.

'I didn't believe an After-Die-Monster scat-pile of that!!', thought Grav, with fury building inside him. 'I just go into dying-monkey mode[fn:: What we would call 'zombie mode'.] and simply say the things I'm /supposed/ to say!', and with that Grav added a twinge of shame to the mix of feelings.

'Why', Grav wondered, 'do I /do/ that?' And whatever he did or said when in that state was pretty much what you would expect a respectable caveperson to do. He thought, 'It works both ways. I /seem/ to be thinking something because, unless I am putting on an act, to the outside person, I look like I really mean them. How do I know that's not exactly what /everybody else/ is doing?'

It was a dizzying thought. 'Maybe others /also/ do and say as I do in those situations.' This occurred to him along with another thought that was surely worth scratching: 'The inner caveperson in another caveperson, was just like my inner caveperson. I am not special. Others are not just /things/ for me to use. I cannot know if there really is someone in there! I will never know, but life goes better if I assume there is another "me" behind other's eyes. And maybe even a friend', Grav felt an odd cringe at that last part that he didn't understand.

Grav and Gog were to be at The Helpful Monkey River-Join by three sun-palm from dawn. Grav sprinted into the clearing with spear and atlatl strapped to is back in not-ready form, and smoothly slowed to a trot. They were only carried for opportunistic hunting. This was another predict-tool of theirs. The prediction was: You could do hunting almost as effectively as you normally do, while doing something completely unrelated that involved walking through the woods. "A Forest Wanderer Never Hunts", was a saying they thought worth wide adoption. For most cavemen hunting was an "activity" and the rest of the time was to be used doing nothing, showing off, or fighting with your neighbors.

Gog was there, clearly lost in thought but aware of Grav's arrival.

In each hand, Grav was carrying a large hemp basket, heavy with the best mining equipment they could conjure.

As Grav approached the glade that at the very crook of the confluence[fn:: Where, legend has it, the Crec clan and culture had its beginnings.]. Taking /the short way/ Grav had to stop and repair the twist-vine bridge crossing The Great Meal Stone's last angry-cauldron, which delayed him a half-palm.

Gog watched expressionless as Grav approached.

Grav knew from experience that one had to pretty much shout over the thunder of the cascades. The Great Meal Stone came from the northwest and The Lame Rhino came from the northeast. They converged dramatically to form the Helpful Monkey, both picking up speed and rage from the steepening, rocky surroundings.

All this angry water out of place created a truly odd and kind of magical Forest-shaking, low rumble that was something like an earthquake that has been ongoing for thousands of years. The dirt doesn't mind. It just gets shaken about. And it turns out plants didn't mind it either, or as many suspect, were just a bit more productive because of the light massage. The occasional tree here and there didn't move visibly, but a hand on the trunk would bring your mind back to the power around you. Trees, and rocks and whatever else hummed harmonically, which added some color to the sea of white noise in the area.

Gog had once put a straight, stiff stick hard against a boulder near one of the more dramatic cascades. Putting his ear up to the other end, he could definitely hear an /audible/ hum that was clear and distinct from the surrounding tempest of noise.

Grav handed the heavier of the baskets to Gog. He shouted, "Whatever we do, let's get the scat downstream!"

Gog nodded, turned, and led the way.

The practiced, efficient jog an experienced Forest-man slipped into while following an established path, especially one that follows a river, became hypnotic in a way that Grav loved. The noisy, often unhelpful part of your mind had no choice but to keep making plans and rapidly solve unending puzzles to optimize one's next steps, which your legs had to perform with a perfect, unbroken rhythm, and sureness.

This also had to be done in time with a rhythm that maximized your breathing and even your heartbeat's efficiency; a serious constraint, if you were a long-term thinker. Exhale on down-stride when possible, especially if you think your heart needs a good squeeze; inhale on the rebound, when your torso unwinds itself like a spring, guided by the big breathing muscles to fill your lungs with air.

The top of your vision saw the upcoming terrain, which you keep scanning for possible complications. In the lower, nearer part of your vision, you make fine adjustments to your macro plans, given new information: This rock has wet moss. That footfall has deer scat that we mustn't stir up[fn:: Hunters knew that if the were just /traveling/ and were willing to sacrifice game abundance in the area for maybe the next few palms, it would definitely do no harm to purposely step in, and spread the scat of any predator, but freshened /game/ scat attracted predators.]. That limb will break if I land this stride on it. And of course there was the built-in constraint of trying to make as little noise as possible, and to not step on anything spiny and deadly, and to continue making no noise even if you do, which added to the immersive challenged that often helped one to think more clearly. So Grav thought at least.

This, he discovered, was a cultivatable state: Get into the groove right away and you'll have a pleasant ride as a passenger in your own body. Your mind is now free to wander about the Forest.

Gog felt the same way. For them, even more than most elite Hunters, traveling through the forest was fast, reliably breezy, pleasant, and just no big deal. It was a kind of lounging for them. It could be done for hours on end with few breaks (which were their own treat), possibly bringing you to a part of the Forest that, despite being a well-traveled caveman of late-age[fn:: A classification to which both men belong. At this time, Grav is 36 and Gog 37.], you had never seen before. And there were landscapes that even these people, however traveled of the infinite, abundant Forest, would stop stunned to gauze at for lengths of time, mouth agape.

This meditation and thinking went on for both men for about three quarters of an hour xxx as they flexed and honed their fundamental survival systems, both muscle and mind. It was surprisingly pleasant to be so wasteful of energy, Grav often thought.

Their usual first stop on this route was a small falls near The Great Crocodile lake, a semicircular lake near a bend in The Lame Rhino. Standing on a high stone on the upper bank, you could see about half of the lake; the far, rounded shore. It had its name due five-man-long, angry bull[fn:: You rightly ask, 'how do we know?' The story is known as "Khrob's Muddy Trap-Burrow"] crocodile that would not bother with you so long as you didn't get within a quarter mile of /its/ lake.

The croc died in the men's youth, but they both remember having to take the shortcut across the adjacent bend in the river, and being lectured by their parents all the while about exactly what the situation was and exactly what the stakes were. Parents knew how and when to scare their children dumb, to great effect. Crec parents were otherwise reputed to be very loving toward their children. Mostly. It was considered a "daring" thing to follow the river here until just about all-finger year ago.

In the comparative quiet, with the nearby cascade only a gurgle, Gog turned to Grav.

"So, I was thinking. These veins run in parallel, probably. I mean, I've seen that in lots of places with regular rock. And the vein goes from within the earth, upwards, which is /also/ where you see the parallel veins in regular rock. A vein of reflect-stone[fn:: Quartz. Both for the obvious reason and also because of what is being discussed here: a vein of quarts has concentrated mirror powers strong enough to create another one, just like it, feet away. It is thought that the formation of a reflected vein of reflect-stone has never been observed because whenever they appeared, they must have appeared together. Crec did not recoil in terror at their reflection. They had mirrors of various types. But they did have a very mystical concept of a "reflection" and didn't blithely play around with mirrors.] often has a twin a few feet or yards away, to one side or the other. And most value-stone grow in neat patterns, just like reflect-stone.

Since we know that the river has eroded much of one side, snaking in and out; it pretty much parallels our first 'vein'[fn:: Gog was being colorful with his language because when they said 'vein' it referred to a /pattern of deposits/ and not much more. It was assumed to be a vein of sorts because it seemed to go in a straight line and keep producing even if you dug downward.], I'm thinking lets concentrate on upstream where it cuts in and out of a vein that might have been there."

"Yup. Sounds good.", is all Grav said in response, having had the same hunch. "But wait, what about the sluice?"

"We will /chain multiple/ sluices if necessary, or make another if that's easier."

"Yaah. Good enough, I guess.", said Grav.

Grav was quite for a bit and then spoke. "Gog?"

"Yu-huh?"

"How do you feel about Father-Brother Verk?"

Gog didn't react but continue to stared at a falls. He spoke softly at first.

"Why?"

"I don't know. Does he seem different to you when you're alone with him than he is otherwise? You know, among the people?"

"Mmm", Gog's eyes squinted slightly.

"I haven't been alone with him much. I mostly just try to avoid that possibility, honestly. I kind of get the feeling that he needs to throw some rocks[fn:: "Let off steam."] /at/ people a lot of the time and I feel like, whoever's job it is to put up with, it has got to be a lot of 'work', if you know what I mean.

Lots of making sure everything's going according to 'plan', but the plan also seems to change over time. Lots of getting into your business if he feels you've got a job to do for him. It looks like he likes to really let lose and let folks know not to cross him."

Grav interjected, "Don't you feel like that could have some push-back? Treating people that way? I mean, he and everyone else knows that he's way up there and above criticism. After a while of that I think a caveman could stop seeing his own faults."

"Heh. Yeah, I have definitely seen that effect in play with some people. It exists like rocks[fn:: "it is a thing"]. And I don't think you're way off the mark.", agreed Gog.

"And also," Grav expended on his unoriginal theory. "wouldn't that kind of thing feed back on itself, rapidly?

If you've driven those away who just /reasonably/ object to whatever urgent thing you're being lectured on, what's left over are a particular kind of caveperson. Kind of the last-part I'll call it. Or no, the 'tail', like what you see disappearing into the bush when you've scared off a big lizard. There's a part that hangs around a bit longer. The 'tail'. Father-Brother Verk's tail of hangers-on are desperate for his approval. They will silently undergo /even worse/ mistreatment by him[fn:: They both felt a stir referring to Verk this way.] which in turn means that mistreatment can /expand/ and meet the new allowance, and so a person's[fn:: Gog was trying to steer back into the /abstract/ caveperson as the topic of conversation.] behavior can get /more/ extreme, which scares those around even more, making them willing to just let any kind of behavior go; pretend it didn't happen. Do whatever, just don't get 'kicked out', you know what I mean? Rather simple people, usually.

Cult of Verk has a long tail." He said without thinking.

Simaltaniously, both shot a look at the other; each noticing an air of shock. Having gotten lost in the indignation he felt welling up, his speech was in sick-monkey mode. He had stopped suddenly with his mouth still slightly open.

Grav continued, with patience. "Father-Brother Verk was a bit on the abusive side with me this morning."

Gog made a pouty lower lip face at him. He pantomimed a child about to cry, with a quivering face.

Grav felt like they were nearing a point where they both just wanted drop the prefixes and the pretense. Their many heretical conversations had a rhythm they both knew well: Adjust loudness based upon scandalousness, try to use a lot of mutually-understandable wrapper language, even when no one is around (and no one /should/ be), and speak the polite deferential, pious parts just above normal conversational volume.

"Uh-huh. Don't act like you haven't been there. Being shunned by The Great Bear on the one hand is just dew off the leaf, but on the other hand, it's like a kind of reality stabilizer that you've known all your life; and unknowingly leaned upon." After two drop-stone, "If you know what I mean."

"I think so.", said Gog. "The whole clan is your close-circle. All of those people deeply admire and revere Father-Brother Verk and if you feel like you're the only one who sees that nasty side of him, it makes you feel like you're going spurned-rhino."

Grav jumped up, in part because it was time to get going again, but also in part out of surprise. He turned in the air, landing on his feet to face Gog[fn:: Being as fit as a monkey, some of the caveperson physical mannerisms would often astound you. "The peak of human fitness" is not any kind of cliche for them. Everyone is pretty close to there out of necessity. And what is more, it was never seen as any kind of burden to them to maintain this kind of fitness. Life was just life. A Crec would leap your 8-foot garden fence with a grunt in the same way you would deftly leg over crotch-high barrier with a beer in each hand.]. Gog continued to sit on his rock with his chin on his fist, staring at Grav.

"That's its own kind of power!", said Grav, /feeling/ the idea more than thinking it.

"Well, yeah. I guess."

"No, think: if disagreeing makes you feel /bad/ and then eventually /crazy/ well...obviously stop disagreeing[fn:: It is worth noting that the men could literally be killed for most of this talk if overheard by any two other Crec. The confidence that they were alone was nearly absolute. No different from assuming you won't some day get hit by a stray arrow.]."

"That's true, brother.", said Gog "I don't even think it takes a bad person, necessarily. Under some circumstances, plain old cavemen will mostly react in the same way. It's not entirely the 'fault' of the individual. It's also not entirely the 'fault' of the circumstances. It's a mix. Like when a lizard-bird's egg just /happen/ to fall into a pond full of crocodile hatchlings[fn:: The lizard-bird does not bother to nest or even land to lay its eggs. It simply drops them while in flight, and always over water. The egg floats just under the surface in what is usually a calm, stagnant, warm lake at the hight of summer, and then hatches several days later. What emerges has nothing to fear from a crocodile hatchling.]. That one lizard-bird pretty much has the productivity of a whole pond to himself[fn:: Yes, Crecspeak has gendered 2nd-person pronouns. And yes they would blithely use this word here.], neatly packaged up."

"It's not the fault of either, kind of. It just is.", said Grav

"Is indeed!", huffed Gog "Let's get there!"

They were off in an efficient run immediately.

The place where they would soon arrive was waiting, with its turned up mud and various mining implements. There were what could be called water-works for processing bulk quantities course, rocky earth for something rare and stubborn.

Gog's helpful contribution, which now looked like a monstrous, tired giraffe leaning over the river as if to drink[fn:: But instead was vomiting ferociously.], was in fact /not/ supposed to be leaning over the river, but no matter. It was a structure that was mostly STRUCTURE. Its long, cantilevered, nearly horizontal span was rather tirelessly engineered, with experiments and all, resulting in a lot of triangles and neatly uniform, arm-thick[fn:: No offense, but /their/ arm, not yours.] spans of twist-vine.

Its justifying feature was a relay of split bamboo culverts that made about a five thumb-pinkie diameter[fn:: Bamboo, being well "engineered", can scale even bigger than this. This was not the biggest bamboo available to them (although this was definitely on the larger side), but, yes, it is far larger than anything you may have seen.] channel for water. Big enough for an all-finger child to use as a kind of water slide, which happened only once. All the splicing work had been done expertly, so it was about as water-tight as a stone channel over a rope bridge, but it could /swivel/. It was fed by the river starting about one and half of one boulder-door[fn:: 100]. men upstream.[fn:: As the math is tedious here: about 300 meters. Crec reckoning is covered in the appendix.]

The floating-sluice swiveled expertly on a conveniently already extant poplar tree[fn:: Pronounced 'wazlic'] about 10 man high and one and one half man around at the base. It had a polished, dense, shiny sections at intervals where the oiled oak bearings burnished the wood, once worked in, the wood was like smooth, ancient stone. This bit of the rigging would last forever. The sluice itself ran out to a fixed 12 men length and continuously gave a heavy, ongoing, cold, laminar punch into whatever it was hanging over. Left overnight, it would gouge a parabolic hole into the river bed three man deep.

The poplar had been chosen for its straightness (among other things). With a bit of patience, the sluice could be tuned and squared up such that two men could work it with long pieces of twist-vine, and some heaving.

It could be shortened at will, down to just over 9 man. Viewed from above, this created a working area in the shape of a three-man wide "ring", with an outside radius of 12 man. There was a one-part-out-of-ten[fn:: The Crec just talk in terms of fractional circles, not "degrees" for example.] pie slice in the ring where the spillway works fed the sluice.

This gave the two men and their "concern" a lot of destructive potential from the local ecology's point of view. They had been making good use of it. One might think that you methodically blast away sections of this great ring and patiently sort through what comes up, and it does go this way in some places. In most places, the pounding water would just completely blast away whatever it was slung over. /Getting/ to that stuff without wasting time or missing anything valuable was the trick.

You could position this blast-zone by swinging the sluice over the un-mined bits slowly, so that it gently (as it were) eats into virgin river bed[fn:: Of course, the river is not a circle. The sluice's arc went over riverbank, ancient riverbed, low cliffs and the like.]. The force of the water was such that more than just silt and pebbles got stirred up. Head-sized boulders would swirl merrily along this twisting torus of purposeful erosion.

"River-Fist", the Workers had named this exciting part of the destruction. 

Irregular, jagged rocks weighing up to about 30 gourd[fn:: A "gourd" was a unit of both mass and volume. Its mass worked out to just over a half a kilogram. Its volume was of course the volume of just over a kilogram of water. It works out to roughly one pound (mass) or two 'modern' cups of water.] would be tossed more or less at random by all this mostly toroidal swirl of water.

The higher a rock ended up on the parabolic cavity made by the River-Fist, the longer it stayed there. Rocks that happen to land toward the bottom of the gouge got knocked around until they were sucked up by the River-Fist again, for another go.

The highest-up of these rocks, if they passed even the most cursory inspection for potential got fetched by some brave, mostly tethered Workers and were thrown as far from the current work area as possible, usually a particular direction or area that was carefully selected after much consideration.

These where the "Feelers". The river water, being completely opaque here for obvious reasons, required Feelers to fish around with their feet and stoop, but hopefully not /dive/ down to fetch whatever healthy-sized rock was there and heave it at least /towards/ the prescribed direction.

This area was often tended by a rather relaxed crew of Soon-Leave to ensure, depending on circumstances, that the newly-mined rocks did not fall into the river or otherwise go missing. They might maintain a berm to check the rocks and boulders at risk of falling back in, depending on circumstances, or sometimes help with the heaving of an especially stubborn rock. A lot of what the Soon-Leave did depended on "circumstances".

Everybody was naked, boys and baby-makers, and covered entirely in smooth, rich clay. It had the look of a troupe of especially smart, uniformly brown monkeys working intensely on some vast, seemingly pointless project.

They hadn't had the Feelers until about three-part-of-four moons[fn:: About three weeks] ago. Inevitably some Worker's child would be flailing around in the already-worked areas and helpfully point out a healthy sized rock that deserved examination. And, quite rarely, but not never did this turn out to be a real value-stone of a value-stone. Before, they had only been collecting stones small enough to fetch as the were cast up near the surface and there had been general sorting and sifting of the surrounding, more convenient work areas. Having learned that some of the massive rocks were worth their while, a new career track had been born.

This was all a lot of work, in case you hadn't guessed.

Downstream of the Feelers were, with the size and age of the caveperson descending as we go downstream, were a squirrel-hoard of Feeler-Lookers[fn:: "Rock-Lookers" before the adjustments.], who of course had to both feel and look for any rock, according to guidelines regularly communicated, drilled upon, and featured in the mandatory training skit, where nervous new-hires would sit uncomfortably, watching the Worker Onboarding Troupe explain the criteria by which they were to identify and handle potential value-stone. And they were many[fn:: TBD, Appendix].

Downstream of the Feeler-Lookers were, of course, the Lookers. These were the youngest and the smallest, safe in the broad, shallow, and now comparatively gentle Lame Rhino. To the extent possible, Gog[fn:: Who somehow ended up with the "cavepeople problems."] would only hire the more clever children for this role. It was easy physically, but it was important and so needed to be done right; to the extent possible.

The Lookers' job was to look for anything of value at all, but especially try to /accurately/ discover evidence that the sluice was encountering value-butter[fn:: Gold]. A river like The Lame Rhino always had flakes of mica and pyrite[fn:: Which they had names for] and these had to be distinguished from value-butter. If even a only flake or two was seen and confidently identified (Gog was always working on an accurate read of 'confident' with these most unsophisticated Workers. It was an ongoing dance.) a number of things were to happen with purposefulness and promptness.

First, the river was diverted to a degree, depending on urgency, second the sluice was stopped.

They were trained to not only use the special resources and keen vision that they as cavechildren naturally had, they also were trained to use two polished obsidian mirrors[fn:: Experimentation continues on the best kind of reflective stone for this, as value-butter has a distinct color different from even that of the best impostors, if one looked closely.], one in each hand, to scan the now clearing water, using an extra couple of doses of sunlight. With practice, the beams could be crossed under water to make a sort of ball of intense light that they could deftly control. Most fell into a rhythm; and just zig-zagged across the river looking intently. A prize, whose value seemed to always to be just more than the one before, was granted to the first child to halt the works for the discovery of any significant quantity of value-butter.

The sluice was "disarmed", as they termed it, first by a shout to the spillway Unit-Leader, high up on the platform built around the poplar to service this bit of the works.

The Unit-Leader would then turn, nod to his subordinate Workers, and unfold his arms to make a vague "get on with it" gesture. The Workers would place a smartly shaped rock called a "boar" in the spillway feeding the sluice and the incoming water, moving at about two man per drop-stone, would hit this specially shaped stone, causing it to create a great "fan" of water, mostly in the vertical direction but slightly off-center. Modern readers who have seen a snow plow will have a good mental starting point.

By the time the water came back down to the level of the spill way, after shooting up (mostly) it was about as destructive as a thrice-in-life very heavy rain. By the time it got down to the great pylons supporting the raised spillway, it was pretty much like a five-year strong afternoon summertime sky-draining. The youngest and least employed played wildly under the heavy, cold shower. Small-ones[fn:: Toddlers. Contrast "quiet-ones"] usually outnumbered the older, working people. Some of them were there with mother or father. Some of them just showed up, and sometimes even spoke fluently in an unknown tongue, and no other. In the latter case, they would usually disappear after all-finger day or so, but the stock would replenish. They were pretty mysterious and impish, thought most of the Crec. /But children are children/, they thought.

Today however, it was 'quiet', as the mine goes. The sluice, while destructive, made no more noise than the surrounding river system. The sluice continued to unload its column of vast weight into the cold river.

Grav had decided, and Gog had not objected, to leave the sluice running while the site was unattended. This would keep the wood wet, and not cause undue wear to the spillway trestle work that surely will add up one day, given enough overuse of the boar. This required someone to remember to stop the advance of the sluice at about one palm from quitting time and let the various lookers and feelers do their work, with increasingly less excitement, until there was enough agreement that nothing more was going to be stirred up. If they were in a hurry (everyone had a schedule) they might back up the sluice instead. This, practice vaguely irked the two men.

Grav and Gog made it into the first clearing of the site, stopping from what had become a near sprint; the obstacles to forward progress haven gotten scarce in the last boulder-door men[fn:: A caveperson's capacity to run through any kind of terrain, keeping the fastest pace allowed by circumstances is practically limitless. The idea was to keep up speed, unless there is a reason not to. There are always rests, but if you /can/ run fast you /do/ run fast (unless there is a reason not to.)]. They were winded but not yet out of breath.

Panting, Gog said, "Let's put in a short day, eh? We'll sit in our office[fn:: This word is chosen because G&G's 'office' was a particular place with a particular purpose and so isn't just some rock next to a tree. They would say 'office' if they could.] and plan a bit more."

"Well, let's get there first so I can both sit down and also hear myself think, if for no other reason." Grav complained a lot about distractions (what other people called "noise".)

The two men headed down a path that most expediently took them to an area that is 1) far from the river and 2) dense with lush, pleasant jungle. Their office was a clearing in such a place, given the possibly overly enthusiastic effort by both to find the "densest" jungle, the office had a roof! The jungle was more 'carved' here, in three dimensions.

After knocking out a lot of growth they were pleased to find that they had a dappling of sunlight for most of the day provided by a mesh above of healthy[fn:: G&G had a Worker dedicated to caring for what they called their 'office-plants', which for here included some structural engineering skills as well.] variegated, fat, yellow-green leaves sprouting from a cobweb of very determined vine whose corresponding anchoring to the ground was hopelessly undeterminable. It was like a fabric woven of living vine, truly.

Not telling Gog, Grav would occasionally find an interesting stem to clip near the ground just to admire the unpredictable lightening-bolt path the murdered vine would trace out inside the cube. Gog was irked, Grav got some fun out of it. The vine's would more than grow back either way.

Gog eventually got determined and after a lot of spying eventually found a cleanly snipped vine near the ground, one or two man into the thick web of vine at the base of a wall, which is a trick to do if your goal is to not kill anything else. Gog was still considering what to do with this evidence.

Grav took to his ham-stone and propped his bare, black feet up on the sand-draw table, that had various important-looking writings on it that each man simply assumed was important, written by the other, and therefor not subject to erasure.

"Oh, I forgot to mention. Father-Brother Verk said that if I found a three deer carcass value-stone, I could skip club-drill.

He looked at his left nipple, wrinkling his chin with his determination to get a better look. Gog looked back without being seen.

"I, uh, said I'd bring him such a stone and /also/ attend drill."

"You fallen-goat! Why the cursed After-Die-World would not just say nothing at all and just /nod/? Child. Do you realize that you immediately took away literally all of your bargaining power in a drop-stone and now you literally have to do exactly that? I mean, /both/ the definitely achievable goal of showing up, **and** finding such a value-stone, which I would imagine I'm going to have to help you with? You prolapsed-rectum."

"Why in the goat-sack would you do that? You... Thanks, brother. A squirrel-horde[fn:: The Crec have roughly the same talent for and perception of sarcasm as you.]."

"Let's get to work", Grav said.

Gog threw a rotted gourd and squarely struck Grav in the back of the head as he walked away. Grav stopped.

Gog was making the hedonistic honk-and-wheeze laugh he makes when the truly funny strikes him. Grav angrily thought about having a talk with the cleaning crew.

"I'm sorry brother! I didn't know that it was both thoroughly rotten and /hard/. We should figure out how to /make those/!!"

Since both men knew the objective and neither was happy about the circumstances, they got to work, mostly in silence.

"You could have gotten /me/ out also, you know?", snarled Gog.

"Oh, you would have stood and negotiated with Verk, huh? Toes to toes?"

"Uuuuuugh![fn:: A surprising amount of their grunts overlap with ours.]", Gog moaned. "Of course I see your side of it. It's...like we were talking about earlier regarding control and such. It's the /could-be-is-not/[fn:: Hypothetical] aspect of it. In /could-be/ you could have negotiated and promised maybe a better stone. Maybe. I donno. Ender-Of-Questions be **mounted**!"

Grav grinned at his friend's enthusiastic use of all manner banana-words. He could be creative, go way outside the standard rotation, and still somehow communicate exactly the nuances of whatever outrage he was in the middle of experiencing. And it was instinctual, like those intricate, hierarchical drum rhythms used by the Balrag.

As both men thought of this as "just the first morning's work", they were taking turns diving at the base of the now relatively calm gouge that the floating-sluice had made since the last work day. They had moved the sluice back in order to have a relatively calm work space.

The sluice would gouge out another half man of depth overnight, depending on conditions, and often enough, something worth examining would be uncovered, sometimes protruding out of the silt like great crocodile eggs[fn:: there has got to be some wild uses for actual crocodile eggs.]. Each man would dive, feel around a bit, emerge take a small break and repeat, for hours as it turned out, because this particular gouge was laden with quite a few frustratingly marginal stones, which, 'marginal' not withstanding, had to be hauled out in order to be examined /at all/.

The two men were exhausted and both thinking it was time to move on to other schemes. There were still a few down there and near the center was the one that both had independently discovered, made mental note of, and didn't discuss until now.

"That one in the middle is especially big.", said Gog.

"Yeah. That contraption we were thinking on to vine those out could stand to be ready about now. That's bigger than the one that inspired us!", said Grav.

"Which, you might add, took four of our biggest Feelers, plus us, to haul out. Only to have Drih smash it to pieces over the course of the whole day, only to find a /couple/ of uvula[fn:: This is the closest and most familiar thing 'pea sized' (and shaped) that the Crav are ever likely to encounter.]" Gog added after some genuine thought, "I think!"

"Welp!", said Grav.

"This looks like a job for the reflect-soul[fn:: mind]. Shall we lay about in on the rocks?"

"After you. I am made of liver.[fn:: Very tired.]", said Grav.

The two men lounged with a clean soul. They already had their day's workout in; sprinting through a 3D maze for the first half, and almost drowning during the second half of the morning. And now they had eaten some of the dried and pressed ambling-feast liver pucks. With sated bellies, they both lounged facing skyward, topping off their philosopher's tans [fn:: Having a uniform facial tan, without any lightening under your eyelids or beneath your nose or chin, is a sign of confident accomplishment, and having serenity of mind. "Upper class" only in that it has a distinguished look, like a neatly shaved face. In a way it means, 'I do not have to work because I am smart.'].

"If we can swing the sluice back and forth at the right speed, we can make the rock sway back and forth in time ever harder[fn:: The men called this technique 'self-shake-rhythm'.]. It's too bad we can't rope it up and..."

"Wait... how can we be made of liver when liver is the thing that gives us the most power?"

Gog stared.

"If our flesh becomes liver, why would we not use that as power?"

"Do you think we actually become liver?", said Gog.

Despite having clever minds, the two men had ideas that were just as firmly implanted as say "God" is in some modern humans. There is no source in shame if you are late in realizing that some things are less literal than other things. Some things went directly from an angry "must not be challenged" to a collaborative "must not be discussed" rather quickly, as this was the only way of handling these things.

The obviousness of it occurred to Gog immediately and he felt ashamed at his naivete.

"Eee..heh. Every now and then one of those pop up late in life for you and you are just so saddened by your reflect-soul."

"Yeah, well, I'm sure I'll top you one day.", assuaged Gog, reluctantly.

"Great Questions!", exclaimed Grav.

"What?"

"We could roll stones down the sluice and hammer it with them. There's enough strength in the water to push some big stones. Maybe even boulders[fn:: Their reckoning was about 273 millimeters, ours is 256.]. We know how to easily pick nice heavy, useless ones. They're all over the place. There's even a good pile of especially big ones near the spillway feed tower."

"Hmmmm...", deeply pondered Gog. "Oh, we could also divert at the falls up river like last time we had to bring the water down. Most of that is still there...obviously. We might be able to get rock-on-rock without any water in the way."

"Ooo. I like![fn:: The literal pronunciation of this expression was 'mi-gewstaah', which overlaps a modern language pretty closely in both pronunciation and nuance, surprisingly.]"

Grav and Gog had clambered up to the falls where a dam had been constructed to divert most of the river several months ago.

The twin of a small-one owned by a Worker interrupted a planning meeting in a panic insisting that his brother was pinned under a boulder. After lots of very focused, serious questioning, the boy said this was about two boulder-door men downstream where the river pinched and became more rapid.

The whole mine had come together to rapidly re-enable the dam to send the river on a different (as of then, virgin) course. The dam consisted of a number of cleverly-fitting pieces, mostly bolders, and could be opened and closed in a short time with enough caveman power. There was lowering the river, and then there was "stopping" the river. There were a few dams. The stated goal of this one was the latter.

They happened to also be shorthanded that day and so worked frantically, if only to recover a body. The men who went and returned from downstream said it was too deep and strong to safely explore possible boulders, of which there were many. The one the boy pointed to was impossible. The best that might be done is to dislodge the body with a long tree trunk handled by many men.

The dam building was completed in about 45 minutes, with only the powerful spray between boulders feeding the Natural river. And a hungry torrent heading roughly at a right angle to the river's original course soon took out trees and made a gorge that would surely need a name eventually.

A chain of men, headed out when it was only just marginal, long enough to peek, peek again, and if possible feel under several boulders, including the prime candidate. The river was also noticibly clearer now, which helped.

An older man who was doing his best to be helpful with suggestions and the general dissemination of information to those who could use it approached the boy. "Now, goat-calf, so you think these men have checked under all of the likely boulders? Could it maybe be the one behind the big one?"

The boy stared at the man and wrung his fists nervously. "I am sorry, sir, I don't know anything about this."

Being struck by the child's answer, the man scanned the river bank to see if anyone else heard or could decipher what the child meant.

As his eyes scanned the nearby Forest, he saw another, rather identical boy with one eye visible in the crook of a forked tree, and the lower half of him clearly visible.

"You!", he pointed directly at the boy. "Come here to me right now!"

With the casual affectation that only guilty children have, he sauntered to the old man's feet, standing next to his brother.

"Is this the brother that drown?", he asked. "Are there only **two of you**?"

"I'm sorry, sir. He said he was going to play downstream. I thought he said 'swim' downstream. I think he threw something big in the river and when I looked, I only saw the splash and kept looking for him to come up.

We cleared all this up just now."

"All-Questions! You troublesome boy. If we ever figure out who you are here with, we are going to ask them never to bring you again."

Both boys ran into the woods and it would turn out, never be seen again by anyone with any confidence[fn:: This was speculated upon and discussed by all for nearly a moon, when work was conducive to idle speculation and clay-talk. A few, but only a few called the mystery 'the twins paradox'.].

On this occasion, the men used the same dam but with some pieces missing. The work was exhausting and they needn't over-do things. The men spent quite a while heaving the boulders into position, each rocking and threatening to topple at any time, and then hopefully being stabilized. Behind this, they put several layers of sturdy woven bamboo screens[fn:: In contrast to bamboo /fiber/ screens, these were literally woven of wrist thick bamboo, which could be accomplished with a lot of steam and crafted lack of perfectionism.].

Once complete, the large boulder in the center of the gouge was not exposed but had only about a palm of muddy water rushing over it. It would do.

As today's boulder was more or less in the center of the gouge, the river-fist landed more or less directly on its top. Having to discover by trial that rocks would take a shorter path than the water, they lengthened the sluice a bit until the smaller trial boulders, heaved as far up the sluice as could be thrown, were knocking on the large boulder's top squarely.

yyy

There were no good places to just pick up mighty boulders and drop them in the sluice. The only option was hauling the biggest boulders they could carry up the zig-zag of ladders to the top of the sluice where it's fed by the spillway. This they did, and after an infuriating walk or two down to adjust the sluice, they had a reliable way to konk the large, intriguing boulder right on its head, over and over, with the biggest boulders they care to carry one half boulder-door men up a series of ladders that verged on stairs but definitely were not stairs and definitely a series of ladders for boulder-carrying purposes.

The heavy boulders caused the sluice to bounce, and so one man would carry boulders and the other would fine-tune the sluice, carrying boulders to the base of the trestle if the sluice could be left alone for a while.

Grav, now genuinely trembling with exhaustion as only a caveman can, felt some frustration at having to send down a promising boulder or two. In theory, the gouge would be littered with conveniently smashed rock. He wondered if they'd be at that large boulder for a while. If it was promising...why not? Maybe do more of this. Maybe the great boulder's real value would be in that of a smashing device for /other/ more interesting rocks.

Having moved the sluice downstream, and with the river still rather low, they reclined productively on the sides of the gouge, each man alternately slipping and scurrying back up the muddy sides, as he did his best to examine pieces of stone found during all the scurrying. The rejects they both wisely decided they should throw in a "smart" direction and so agreed on a certain spot over the berm where the bank (of /some/ river) was closest.

"I've seen a few. You know where I'm tossing them.", said Gog.

"Yep.", said Grav, still exhausted and not recovering much.

"So... it's not a failed-hunt and we found some good stuff.", said Gog.

"Yeeah, but there is 'no get out of club-drill' sized value-stone like we'd hoped."

"Nope.", said Gog.

"Nope."

Grav and Gog got their gear together, knowing that this was enough for one day. It was only one-palm-after-noon or so but they hadn't intended to make a full day out of only this, and Gog hadn't expected to get drug into a lizard-bird-hatchling chase. On some days, the exhaustion told you it was time to quit before the sun did.

They passed through the "interesting" pile and toed around as they always do out of habit. Gog, with his toe, not bothering to bend down, pushed around some head-sized rocks to see underneath, as a strategy for maximizing rocks-inspected for given effort. He could indeed "toe" entire torso sized boulder, to an extent, having an intimate understanding of rock dynamics and legs that were made out of iron-tree[fn:: Yes, the very same tree with the very same name.].

One rock that he had only touched with his toe, and then reconsidered, moving on to others, made a sharp "click"[fn:: The two men had a more or less modern-human ear. The majority of this 'click', while still sharp and clear to the men, was in the ultrasonic range and caused two incongruous bats cruising the bright blue morning sky to make a u-turn.].

"What the sew?", said Gog, who was the only one able to connect the sound with the cleanly split rock just next to his foot. Grav turned and followed Gog's gaze, instantly making a face to match his; one of wonderment.

The oddly uniform, oddly oval, oddly beautiful-on-its own stone had been split in two by a perfectly flat planer separation, that Gog had to repeatedly swear there was no hint of before the audible crack.

Instantly the two men felt like they were the caretakers of one of the most wondrous objects anyone had ever seen[fn:: They would have sought traffic cones and bright black-yellow tape if they knew of such.]. Together they first scuttled along the slight grade, one on either side, and then stopped and knelt on one knee to look.

The inside was just visible and it was apparent that it was as uniform, smooth, and shiny as a puddle on a very still and quiet morning[fn:: Ideal to check your teeth for signs of breakfast.]. They beheld a smooth, uniform, grey croc egg, split long ways, exactly.

Peering inside, between the gap, to see exactly what was there was frustratingly hard, as the crack was no more than a few leaves in breadth.

"It did that a good five drop-stone after I just /touched/ it with my toe. It's like it was already under some force and was just waiting to break."

"We /have/ to pick this thing up and some how check it out, but I am terrified that we'll break something inside that is likely to be a once-in-life find.", Grav said while thinking. "You know... that thing is /heavy/ I remember it specifically, admiring how smooth and perfect it is. I had to give it an extra good heave, but it managed to fly a bit high, despite my instincts and landed here with a very solid 'crack'. And /that/ didn't do this. Your /toe/ did?"

"Yup."

"We should maybe start by removing some silt? Maybe grab a gourd or two of water while we work it away. Go get some, would ya? Our drinking gourds are just upstream. I mean, yeah... I'm like you; the suspense is killing me.", said Gog.

Grav returned with two gourd of water which he gently poured over the the rock while Gog cleared the silt. They both knew that, whatever's inside, it's not going to be bothered by some water. Nothing that has spent the whole before-and-after-questions in the earth was bothered much by water. They repeated this with an all-finger or so of gourd.

Another thing a rock of any kind can tolerate is some gentle nudging with a green twig. Grav explored the parameter of the crack making mental notes. "I'm going to say it: It's exactly like there is a yolk in there."

"Yum!", said Gog. "Maybe we should just secure it in this position and take it back to the office."

"I suppose. Some bump or disappointment or other is inevitable. Let's do that and knock out the ceiling. I think it's worth it for this.", said Grav.

"I reluctantly agree with you.", said Gog.

Having gently wedge in some green, spongy twigs into the gap and wrapped the whole "egg" with twist-vine, they used yet more twist-vine to lash the stone to a couple of poles to make a kind of litter.

They both raised the stone to hip hight slowly, expecting another strange surprise underneath. It turned out to be just more stone and mud, unsurprisingly, as this was not its...birth place, so to speak.

They worked their way up and down slopes, trying to keep things gentle and smooth, if not always level.

Midway through the clearing, between the closest of the worked river basin and the beginning of their office entranceway[fn:: which was a 15 man long.], both sticks suddenly and unexpectedly snapped where they came closest to the rock. The precious bundle was allowed to fall a good half-man onto an inconveniently placed sharp rock.

There was no longer any need to discuss how to get the thing open and which long and painful protocols to follow, the stone egg gave up its secrets right there on the muddy clearing, both halves rocking almost mockingly for a good few drop-stone, the "yolk" sliding back and forth on the smooth inner surface, refusing to fall back into its form-fitting void /or/ fall of the edge.

The two men, useless sticks in hand, stared silently as the two halves came to a standstill.

They stared some more.

"It looks like a rock-stick.", said Gog.

"Uh. Yeah. Like, a lot."

They continued to stand there, smiling looking at the strange scene before them, shaking their heads[fn:: note xxx on head shaking?].

And for a while after the rocking stopped. They took turns making the involuntary, soft, high gurgle of the dumbfounded.

"Now, this creates at least one serious dilemma.", said Gog. Grav watched him as he spoke with a face that said, 'I know, I know'. "This is, as hoped for, the biggest value-stone that we or possibly...probably anyone has ever seen. And yet, it looks like a big, fat boulder-stump."

Grav snorted despite the unreal circumstances. Neither have seen anything remotely like this in either size or character. Character carrying a lot of the weight in this case.

"See, if we show this..."

"Obviously I get it, Gog."

"Maybe if we just play dumb? Maybe if we dress it up?"

"Do you want to put a ceremonial palm-skirt on it?"

Both men laughed.

Grav was holding it in his hand in the least sexual way he could manage, inspecting it with wonder. It was a scapolite[fn:: They call this iris-stone, as it sometimes looks in color and richness the medium-brown iris that is universal among them.] about one and one half of one pinkie-thumb long,  ...penis that was plausibly not shaped by human hands. It had the right amount of "organicness" to it that might cause one to think, rather, it instead looks more like "the real thing", but its shape was also distorted in some places and ways that led one to think just long enough: "nah." But then again: "yes, somewhat."

It was something that /might/ be benign looking enough to show grandmother, if you coily avoided her eye for the first few drop-stone after revelation, looking at your fingernails, say.

It was a kind of crypto-stick, for it did lack rocks. And was blunt at the "bottom", as though this was exactly what the crystal did: make a big human penis, and then stop abruptly when done. Being wet and muddy as described, it fell and stuck halfway into the mud when Grav made the mistake of trying to hold it by its "base" and relying only on his vice-like grip on muddy stone. This could have been seen as a kind of warning to future handlers.

"Stupid-ham, you're going to break it.", said Gog.

"Somehow I get the idea this doesn't break easily.", said Grav.

"Yeah. It's taken a beating already. Did you notice its little 'cubby' is shaped, like, I mean /exactly/ right? It's like implausibly-unreal[fn:: Magic.]. It's a zero-allowability fit."

"What the Afterlife, brother. I am legitimately weirded out by this thing.", worried Grav aloud.

"Well," Gog said, "I am just going to follow a xxxhypatheticalxxx here, a xxxthought-experxxx...what if we just totally play dumb, all day, every day[fn:: Pronounced 'dakom!'] and never let on. So we found a lifetime value-stone...so what? Do you expect Father-Brother-Wife Kham to say to us, 'Hey, boys, don't you think this looks like a big stone-branch?'"

"Heh, that's just crazy enough to work, brother.", said Grav.

"Exactly!"

After washing the whole works in the river and scrubbing lightly with the finest silt they could find, they let the three pieces dry on the rocks for a palm or two and talked.

"Let's just decide right here and now that neither of us are going to crack. It's like a secret you're sworn to keep, except in this case you are obliged to always keep up an act: We have no idea it looks like a grown-man's pebble-twig. We think it looks more like a kind of fish we saw once; exactly like that kind of fish! We're biased in that direction. We are deaf to the innuendos of even our closest-circle.", said Gog with some certainty.

"That's hard." Grav watched Gog nod his head up and down. "I mean with, say Father-Brother Verk, that's easy. With those all-finger-and boys that like to ask for feedback on their banana-language that corner us just out of town[fn:: The Crec's concept of 'town' was any place where you stopped seeing occupied caves for a bit. When you suddenly realized this, you were out-of-town. It's a concept that has the subconscious as part of its definition.]. They're always guffawing and, despite myself, I find myself wanting to one-up them with the banana-juggling[fn:: Shit talk, smack talk. See the appendix about 'yo mama' jokes.]."

"Yep, including them.", Gog said, demanding total surrender to the plan.

"You shit-pile on it too?[fn:: All boys at some point would have a shit-pile ritual. It's like a pinkie promise, except, to signal the gravity of your oath, would shit on top of a freshly laid shit made by the other boy. It has its parallels in our world. Among men this was said ironically, as all promises made by true cavemen are actual, legitimate promises, rituals aside.]"

"Yep. I'm in. I think it's fun to mount human behavior just for the colliding-stamped aspect of it. Is any of this /wrong/? I mean, I don't think for a second that it is. How, omitting our opinion about what something might look like? We cannot decide not to take sides? Maybe we begrudgingly see a similarity but lots of things in the Forest have that shape."

Gog: "Yep."

"So, as absurd as everything that has happened in the last 10 palms is, I think we need to focus, as I assume we are caring that sinful bulk back with us.", said Grav.

The two men carefully packed the objects in dense, soft leaves and used (and reused) more twist-vine to secure it into a safe, padded ball as a first step. It was still deeply perplexing that the whole bundle had fallen apart seemingly spontaneously.

The then made some heavier twist-vine, with which they suspended the bundle from a sturdy pine trunk with two all-finger passes.

After the men compared mental checklists before leaving, they hurried off toward xxxxx, leaving whatever they could behind.

They decided to stash it nearby in one of their plentiful "perfect" locations and make a day out of planning and "presenting" the find to Verk in the optimal way.

And so they did. The entire next day was spent trading and criticizing aspects of all of the aspects of this weird /thing/ they were doing. In their optimism, they decided that, while they may not be able to skip club-drill, they could milk this "penis"[fn:: Only you will be able to appreciate this bit of the author's humor. The Crec had no saying that is adaptable to precisely this joke.] thing in ways that more than made up for it.

As for practicalities, they of course continued to agree, like cavemen, to abide by the mutual decision to play it coy. This was not hard to do, it turned out. Those that "saw it" were shocked into sick-monkey mode, forbidding all of their being from acknowledging the now obvious. Even in front of a couple of cut-ups like Grav and Gog.

They also agreed to just lay the pieces together, on its side with the top stone naturally pressing things together, and let Verk, do the official revealing, an invitation which Verk literally could not conceive of declining.

There was no mention from Verk about any possible excused absences from drill for anyone.

Verk had gathered a medium sized crowd into the ancient-speak burrow. The soon-to-be-revealed mineral wonder that the men had to ensure Verk was really there was still awaiting revelation. Verk wanted his own surprise to be genuine and so went along with the men's enthusiasm in describing the find, knowing that over-selling a thing that turned out to be a disappointment for him is something the two boys would include in their calculations.

On the off chance that this was to be underwhelming, Verk tempered his urge to invite the whole clan. He could always claim that, "While exiting, we needn't bother the children with the overwhelming wonders of science[fn:: For most Crec, science just meant 'pretty cool, but in a smart way.'] until a group of /distinguished/ adults had a good examination of it first."

All invited were present, introductory remarks made, grateful nods made towards Grav and Gog throughout. The quiet chatter among the adults, some giddy, had died down rapidly with an expert cue from Vert; only a small change in his stance and facial expression.

"It is time, my fellow cavemen.", I sure hope you brought us something grand, Grav and Gog, and we thank you for having the heart to make a gift of this mysterious find to treasury of The Forest Heroes' Fallen Cavebabies Fund[fn:: This is a fund enjoyable only by Forest military veterans to help with the care (or funeral, as appropriate), should any of their offspring be injured or killed in a fall, which happened very regularly of course.]..

Grav and Gog stood smiling awkwardly. The crowd was too small and close for there to be any idea which direction to face. They felt on display as well, with Verk maybe doling out a bit too much praise to keep the boys' sense of obligation sharp.

Verk did a triple-take with a broad, yellow smile for the clan portraitist and anyone else with a keen memory. He pried the two halves apart with a fine, glittering Sky Clam halve[fn:: These were found on the top of nearby /Mnt. Fish/. No one knew how or why.] and a healthy-looking, tough, thick, velvety leaf which he used to protect the perimeter of the mirror-stone finish he had been assured he would find, among other wonders that he insisted remain a surprise.

The two men had never felt this kind of intense, surreal terror before. Either their predict-thought was correct, and Verk would not /see/ what was there, or he would immediately see a fine, sparkling, extra-large false-rock-stick that would, should such a thing even exist outside of caveboy talk, be hidden carefully under feet of bat-scat in the very back of one's cave[fn:: Which would keep it quite warm, which no one found out.].

Verk grunted the desperate grunt of the soon-dying and heaved the top halve upward, balancing on the bottom, thick end of the "egg". The top halve slid slightly to warn of its instability. Gog and Grav each picked up the fatter, heavier half, one on each side, and the three men walked it over to one side, setting it down on a blanket of fresh leaves. Gog could see the revealed form, while Grav was walking his share of the heavy half of the egg along, with his head turned, but both men felt the same hopeless terror combined with an oddly sweet giddiness.

"My sweet Ender-Of-Questions, in its hammock above!", Verk covered his open mouth with the fingertips of both hands in a somewhat dainty gesture, and smiled warmly. "It is /astonishing/.", stretching the syllables.

The men watched Verk shake his head slowly as they wondered which way this was going.

"It's /beautiful/!", Verk paced slowly in a semi-circle as the small crowed, also gazing and cooing, made room for him.

Verk lifted the smooth, clean, glittering brown crystal from its perfect den and held it up with wonder, letting the soft orange of the late afternoon sun coming from the nearby cave opening reveal all of the object's beautiful, strictly bilateral symmetry with the contrasting powers of well-oriented, bright sun.

"It looks like /something/...", wondered Verk aloud. "It cannot be other than a message. To comprehend what Ender's-Nature-Force has revealed to us is of the utmost importance. It is a message to us, to the Crec, straight from Its mouth[fn:: "God" was a more abstract being to the Crec than ours is to modern people. Referring to their 'god' as 'it' is in no way a kind of sacrilege. It is the pronoun to be used. For, Kug, Great Diviner of Recent Messages said in his youth, 'The Crec God has no rock-stick!'. In other words Ender-of-Questions was genderless and what is more, not thought of as 'caveperson-like' in the least. They would find the idea so humorous that, should you some day be able to inquire about theirs, offering a description of your god's nature, a revealing conversation would likely not be possible. Ender-Of-Questions /does/ have a mouth, though.]."

"Indeed Grav and I thought the same thing.", offered Gog.

Verk turned to Gog, "Young buck you may be wise yet.", and smiled with a wink. This was a cue for all present to appreciate Verk's dry wit, which they did with apparent sincerity.

"Let us pass it around the room! Us Under-Men[fn:: An near analog of the modern Japanese 'kouhai', one's social inferior in some given context, in this particular case the speaker was thinking in terms of their shared military experience and shared love of knowledge.] are thirsting of curiosity."

The small crowd of men in the large burrow took turns handling, admiring, indeed caressing the object. There was many quizzical raised eyebrows[fn:: Being mostly 'biological hardware' in origin, this gesture means the same to pretty much all of humanity and their cousins.], asking 'What can we learn from this?'

Some of the men, while holding it, managed to quickly have something to say to their neighbor, causing them to just as quickly pass it along. Some made an admiring smile and gave a sideways nod, with raised eyebrows. Those who decided they had something to contribute to the discussion sometimes missed a beat or two in the animated group conversation's rhythm, and stepping in at not quite the right time, said things like...

"Could it be just the front one piece of four of a kind of viper, perhaps?"

"I have seen weapons much like this!"

"Are these not gills, Kvred? Could it be a fish? For it has a kind of small mouth. I have seen a kind of dart-fish that has pronounced dorsal muscles producing in a similar, long, thin snake-meal along the bottom-center.", at which Kvred looked nonplussed, as if to say 'why are you asking me?'.

This contributor, smiling and not looking at the crystal, ran his fingers "down" the "bottom" of the object; some others noticing his unkempt fingernail as it glided slowly along the crystal's surface to point out this structure.

"Does it not look incomplete to anyone else?"

"Things in Nature do not have abrupt, sharp ends like we see here." (pointing) "Unless it is cleanly cut by a blade, like the fallen arm stumps we may see in glorious battle."

The group of men mostly looked at the floor and seemed to be pondering this remark further.

At all this, the amount of apparent blindness to the obvious may be striking to you. After all, the Crec were naked an /awful/ lot of the time, seemingly without shame. Some keen students of humanity see this kind of dissonance all the time, even in their own cultures. What one does with this kind of observation is what's important. Rarely is it pointed out recklessly. The sick-monkey way in which humans reinforce this kind of willful social blindness "at all costs" can result in literally violent reactions from anyone forced to see what they /need/ to remain hidden forever.

"Father-Brother Verk, what shall we do with it?", asked one of Verk's Under-Men.

"As a gift to one of the Elder-Quorum's finer charities, it will of course make its way eventually to the Hard-Guard-Cave, but tonight it goes home with me, so I may ender-talk with The Ender and try in my humility to divine his message. Made-Baby-Wife-of-Verk[fn:: See Appendix: 'Language and Naming Surrounding Women'.] and I will ensure it encounters no ill abuse."

"Very good, Father-Brother Verk! Gog and I will package it in the manor in which we did for its movement from the mine. We encountered problems with our first attempt. It seems to have some tricks up its sleeve[fn:: Not having shirt sleeves, the Crec actually use a very similar expression that roughly means, 'magic in my garments'.]."

"You are a fine help.", said Verk, his face expressionless.

The two men, having most materials already handy, re-secured the egg and its yolk, hanging it from the same well-suited springy tree branch. Hoisting the xxxx over to two of Verk's Under-Men's shoulders, who watching Verk's retreat towards the exit, hastily set off in a trot towards xxxx verk's own local hill xxx passing Verk as stopped and turned at the exit.

"Oh, boys.", Verk said with one foot still pointed at the cave's exit way. "See you at club-drill day after tomorrow?" He smiled, showing apparent warmth, placing his hand over the springy mat of white hair over his heart, and pausing for an answer.

"Oh, yes Father-Brother Verk. Grav and I will be there one palm sharp!"

The two men saluted by grabbing their left ankle with their right hand, locking their right knee, straightening and looking straight ahead at infinity with their shoulders square. "With the mind of a rutting ambling-feast, in a great blizzard, our Upper-Brother leader Father-Brother Verk! We will be there!"

Gog said this alone as Grav did his best to make broad, sincere eyes. The men had not yet mastered speaking-as-one-in-battle[fn:: The meaning is obvious if you think in terms of the need for soldiers to not only act as one, but to literally think as one. This is a resource that modern humans are almost entirely without. A fierce sense of personal sovereignty that exists, even in remote, simpler communities of any left-over bit of 'primitive' culture still present in our world, in all modern humans has been a kind of wrench in the works of humanity, but also a great blessing. Humanity took a kind of fork in the cultural progression road, some time long ago. With practice the Crec, any Crec and most tribes known by them at the time could, when under extreme duress where lives or maybe whole cultures are at stake, literally respond as one to their superiors, so thorough was military training. One helpful factor, in your defense is that battle lacks a lot of nuance and the overall tasks are few.], which is a practice solders of at least mid-rank were expected to do.

Verk squinted and stepped out into the pink late afternoon.

"Farewell for now, boys!" Verk strutted out of the cage with that energetic "walking uphill" look, with exaggerated arm swings, that unmentionably fat cavemen have.
