#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="index.css" />
#+OPTIONS: num:nil

(At-Least-For-Now-Secret Notes about /Gog said "Boulder-Stump"!/)

Everyone is a caveperson. It's as appropriate to say "cavelady" as it is to say "lady".

The feeling is light and easy like a mockumentary. The narrator is just "me", so I don't have to remember what "voice" I'm using. 

* Outline

Everything is subject to change, eebureetang. But you'll have to retitle if we don't have a smackdown involving Gog's use of the word "boulder-stump" somehow.

** Ch. 000 Preface

We meet the Crec and learn about their world. Verk tells a story. It is deeply meaningful for some.

** Ch. 001, wherein we learn of Zog's great acumen and fertility

We take the reader back to Zog's early years. Zog current clan leader, and that's why it's called "The Zog clan". Zog was a hero's hero, in other words, lucky he's not dead. He was known for his daring and just kind of /falling into/ situations that make him have the appearance of a total badass. He just happens to be the guy in the good -vs evil movie that throws the rock that seriously wounds the bad guy in the satisfying end. Roll credits. But despite all of his impressive doings, he really only has so much of a clue what's going on. He's not learned to have a look of wonderment when things work out for him. Giving the impression that he meant to do that all along is central to his persona. This means giving some pretty weak and convoluted explanations. We hear the perplexing story of Zog's first dive, and as far as anyone knew, first dive ever in the tar pits. He came off looking like a total stud, but came within seconds of dying about eight different times in the process.

Let's have a from-birth to marriage fastforward, followed by tales of daring from his youth. And of course, displaying, entirely for what it is, his deeply held, more or less random believes that he's willing to club-fight over. Lots of adventures. Lots of badassery.

The lesson? There is a right way to be a Crec. Zog simply exemplifies it.
...
** Ch. 00~, wherin Grav starts studying to become a lawyer (though we have a clever name for it)
...
** Ch. 00~, wherin Gog scratches "boulder-stump" into a soot-pallet and shouts it from atop Lame-Monkey Mountain three times on a dare
...
** Ch. 00~, wherin the Make-Stop-Banana-Word Commission of the Elders-Quarum begins proceedings to update the list
...
** Ch. 00~, wherein Zog distracts from the business of the Elders-Quarum with an incident involving a hyena
...

* Relations

- Grut, haver of potent seed, starter of epochs. He actually does not have an appendage of any kind to his name. He is just "Grut", not "Grut The Something". His time is as far back as memory goes. He and his only wife Jaar are the founders of what is /now/ called the Zog clan.
- Would like too mechanize this and make a pretty diagram, maybe a python script.

* Notes

- No humorous-fake-terms for things that /they/ have and /we/ have a name for. For example, no need to call a tree a "massive-weed" or to call a cat a "gerbil-dog". Or maybe yes do that. It would be pretty sweet if Crecspeak words got a special tag so we can identify, use special fonts, check for glossary leaks...

* Ephemeral Notes

- "boys and baby-makers!..."
- Someone gets caught using the "bachelor-tree" and is vaguely shamed for it the rest of their life.
- We need to get around to: Gog said "boulder-stump" and is tried for obscenity and has Grav as his lawyer.
- Somewhere here and there we need to throw in a "very special" episode where someone get's gorily torn apart or beaten to death or thrown off a mountain for something that totally deserves it: man-on-man buttfucking, conning granny, child-diddling, disrespecting the Chief... Really shock it to 'em.
- Is there a character that's always trying to make a flying machine and fails over and over in hilarious ways. Is there?!
- There needs to be a skill or activity that makes a caveperson really look like a badass. Like taming a hyena and riding on its back (which works out usually.) And a regulatory body that ensures that only the properly skilled are allowed too operate a hyena. They should probably have to wear some kind of coconut helmet, by law. And polished amber sunglasses: Crec-Bans.

But what's the plot?

* Crecspeak

Words transliterated from Crecspeak are always hyphenated (or /dashed/), like "father-brother" meaning your father's brother, and not /just/ uncle. The distinction is important to the Crec.

For the English speaking audience, we use the closest equivalent in English to determine capitalization. For example, "Do you have a father-brother?" vs "I saw Father-brother Verk".

Be careful not to over-think the meaning, but it should be apparent from context. The words are chosen from English to best convey the meaning. It may sometimes be hard to understand why certain words were chosen. In these cases we are trying to convey the meaning as a Crec would understand it.

** Glossary

- after-die-monster: Their Devil. Just one, like you.
- ancient-speak: Generally meaning "story-telling", this analogous to selling a book in our times. It is both 1) revered by default 2) kind of, let's face it, not always going to be a big deal. Times change, pops.
- baby-makers: Girls. I am sorry. My job is to bring you this story accurately, including look /and/ feel. This was their world, sorry. But a Crec, or perhaps even any caveperson would have no less respect for a /mere/ baby-maker than you would for say a truck driver or computer technician. It's due its own respect, in their eyes. And everyone gets along, no less than you and your sister did. It's just what's up, that's all. 
- bachelor-tree: A defecate, oddly "chubby" tree that both looks and smells like wedding night. It is also a very delicate topic of conversation among the Crec. Sure, the Amish might know what a vagina /is/, but will somehow manage to go a lifetime without saying it out-loud or acknowledging its existence<footnote: ever, ever, ever> (to reach for a tangible analog you might understand.)
- Battle of the Snake-Meal, The: Without a doubt the most famous battle from The Great Club War, and its turning point in favor of ultimate victory for the Crec.
- between-ham-fire-pebbles: Hemorrhoids, piles.
- bird-scat: Used variously for snot, puss, and, if you are a particularly nasty sort of Crec, semen.
- boulder-rhino: A kind of engine of war that is know by many names in our world. At its simplest (which it usually is), it is a collection of the largest stones that can possibly be hauled to the top of the hill/mountain, restrained by a few smaller rocks that will somehow be swat out of the way at the right time, releasing a thunderous stampede of very big boulders, in the direction of one's enemy, most often.
- boulder-stump: Here we reach /the/ word around which this entire story orbits. You'll figure it out. It's pretty embarrassing after all.
- burrow: The Crec use this word like we do to mean an animal's dwelling, under the ground or in a rotted tree for example. They also use it to mean "room", "cave" or any other more-or-less person-sized void made in rock or sturdy earth for the purpose of occupying, even if only for a drop-stone.
- Clorp [singular and plural]: TODO: who are then and what makes them tick. They are the "enemy" of the Crec. And a definition.
- club-fight: A kind of duel involving some ceremony. There is a regulatory body <why not name it here> that exists to ensure that any two clubs used in a club-fight are recognized as being "fair". The participants, on the other hand vary widely. The last rule of club-fight, as it is the most important, is: Someone's got to not be able to walk away.
- Crec [singular and plural]: The Forest to which the Zog clan both lives and belongs. "Crec" can refer to the Forest or the people who live there.
- drop-stone: A unit of time; about as long as it takes for a stone to hit the ground when dropped from an outstretched hand, on more or less level ground. They're as tall as you and used to inhibit the same planet. You figure it out.
- elders-quorum: This is a sort of "The Senate" of a Forest (in cases where they have bothered). It's just as inept and entertaining as our analogs (diet, soviet, merikin, parliament, kremlin, house, neighborhood gang...)
- father-brother: Your father's brother. Your "uncle", but with more information.
- food-clay: Shit
- Forest: The largest organizing category of people, analogous to a nation.
- Forest-Deer: A political party (same deal) that composes exactly 50% of the Elders-Quorum (You should now be asking if these are the good ones.)
- juff: An alcoholic beverage made from fermented coconut flesh, and a polite quantity of spit from a special, designated virgin baby-maker, who is chosen yearly as the designated provider of spit (A custom that has been known to ruin some plans.)
- jump-scare: Living in something like a giant ant hill, opportunities to e.g. hide around the corner and scare the food-clay out of someone abound. This is that.
- predict-tool: Probably a good start on the idea of "a hypothesis".
- relax-marks: Everyone sits on rocks. Some rocks get a lot of mileage. Inevitably there are brown, burnished areas that repel liquids well and indicate a sweet rock to sit on. So there is some tension: On the one hand they are a mark of shame, sloth and bad housekeeping, but on the other hand everyone likes a good sit.
- rhino-calf: It means literally that but is also a term of endearment that you can still say without being too creepy. Like "dear".
- rhino-scat: Mostly known as being the name of a certain hill that was central to the events of The Battle of the Snake Meal during The Great Club War. Actual rhino scat has a certain look. The famous hill has that same look.
- rock-stick: Referring to the cavemen sex organs, it has a slightly less "rude" sense than do other profanities. It's equivalent to the modern (circa 2021) English "weener" or "peener" or "willy" or "pee-pee" or "jiggly bits" or "hookie" or "wee-wee" or "peter".
- several-finger: A quantity of something. It is exactly 10. The number of fingers you have. Like "dozen" but two less.
- sit-ham: Butt-cheek
- sit-ham-stone: Chair
- snake-meal: A "bump", "lump", "protuberance", "hump", or area of fattening. Also used in the way we say, "love handles".
- soot-pallet: Wherever fire has deposited soot on an area of stone that has been used for writing, if you write in it, it becomes a "soot-pallet". It's as common as and thought of like billboards, but are not thought of as owned, so it's acceptable for someone to write something (proper) on such a sooted stone surface. Trespassing is still a thing, though.
- squirrel-hoard: An abstract quantity meaning "a lot", if you thought "a whole bunch of" you'd be close.
- sun-palm: A unit of time. The amount of time it takes for the sun to pass the width of one palm at arm's length. For example, if you want to know what-in-the-morning it is, hold your right arm out straight, rotate your upturned hand counter clockwise 90 degrees so that your fingers are pointing to your left, the distance from top of your hand (the outer [upper-most] part of the first knuckle of the pinkie) to the bottom of your hand (the outer [lower-most] part of the first knuckle of your index finger) is the unit you use to measure the hight of the son. A Crec will say, "It's 7 sun-palm from dawn, get a move on!"
- take-money: Shorthand for take-part-money. Take-money also means "robbery" or "mugging", but the Crec universally do not make the connection.
- take-part-money: A tax.
- value-stone: A unique, hopefully big, visually appealing gem or mineral (there are many sources.) They are the currency, but their relative value is determined at haggling time, which makes for double the arguments.
