#+title: Notes About /Gog said "Boulder-Stump"!/
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="index.css" />
#+OPTIONS: num:nil

* Crecspeak

Words transliterated from Crecspeak are always hyphenated (or /dashed/), like "father-brother" meaning your father's brother, and not /just/ uncle. (The distinction is important to the Crec.)

For the English speaking audience, we use the closest equivalent in English to determine capitalization. For example, "Do you have a father-brother?" vs "I saw Father-brother Verk".

Be careful not to over-think the meaning, but it should be apparent from context. The words are chosen from English to best convey the meaning. It may sometimes be hard to understand why certain words were chosen. In these cases we are trying to convey the meaning as a Crec would understand it.

** Glossary

- after-die-monster: Their Devil. Just one, like you.
- ancient-speak: Generally meaning "story-telling", this analogous to selling a book in our times. It is both 1) revered by default 2) kind of, let's face it, not always going to be a big deal. Times change, pops.
- baby-makers: Girls. I am sorry. My job is to bring you this story accurately, including look /and/ feel. This was their world, sorry. But a Crec, or perhaps even any caveperson would have no less respect for a /mere/ baby-maker than you would for say a truck driver or computer technician. It's due its own respect, in their eyes. And everyone gets along, no less than you and your sister did. It's just what's up, that's all.
- bachelor-tree: A delicate, oddly "chubby" tree with soft lacy leaves that both looks and smells like your wedding night. Small burrowing animals like the bachelor-tree because its soft, incredibly wet flesh makes burrowing quite easy and the natural internal heaving of the tree ensures that it is a snug, sometimes very snug place to burrow, especially in the dry season. It can be problematic for burrowers to breath, because of the snugness and most will usually nest with just their noses sticking out of the opening. Because small tree-dwelling animals are predominately nocturnal, animal burrows in the bachelor-tree are almost always empty at night. This is also a very delicate topic of conversation among the Crec. Sure, the Amish might know what a vagina /is/, but will somehow manage to go a lifetime without saying it out-loud or acknowledging its existence[fn:: Ever.] (to reach for a tangible analog you might understand.) [TODO: the complex bachelor-tree reproductive cycle should *depend upon* cavemen.]
- Balrag: A tribe that borders the large, thinly populated region to the Crec's south. From north to south: Bhorv Zolk -> undesirables -> undesirable's-undesirables -> next tribe over (Balrag). As it was both downhill and a good bit south, it was noticeably steamier. Gog or Grav would struggle for something meaning "exotic" to describe the milieu[fn:: A meaning they understood, but a word for which they might struggle.] that was Balrag Culture[fn:: They were fans.]. They had a style of drumming that was considered by most Crec to be a "bit on the carnal side", with rhythms that merged on scandalous. It was known that they rarely scratched any of their drumming down, even if improperly. Their drumming was loud enough to be heard softly but distinctly on a calm, clear, crisp [omg what is "Christmas"?] night...usually long past midnight.
- Battle of the Snake-Meal, The: Without a doubt the most famous battle from The Great Club War, and its turning point in favor of ultimate victory for the Crec.
- between-ham-fire-pebbles: Hemorrhoids, piles.
- Bhorv Zolk: The cave "system" in which the Crec live. Properly, it's the name of the hill that the cave is dug out of, but the two concepts are more or less interchangeable.
- bird-scat: Used variously for snot, puss, and, if you are a particularly nasty sort of Crec, semen.
- boulder-door: A quantity. Exactly 100. Reckoned to be the number of boulders to keep handy to barricade the average cave entrance.
- boulder-rhino: A kind of engine of war that is know by many names in our world. At its simplest (which it usually is), it is a collection of the largest stones that can possibly be hauled to the top of the hill/mountain, restrained by a few smaller rocks that will somehow be swat out of the way at the right time, releasing a thunderous stampede of very big boulders, in the direction of one's enemy, most often.
- boulder-stump: Here we reach /the/ word around which this entire story orbits. You'll figure it out. It's pretty embarrassing after all.
- burrow: The Crec use this word like we do to mean an animal's dwelling, under the ground or in a rotted tree for example. They also use it to mean "room", "cave" or any other more-or-less person-sized void made in rock or sturdy earth for the purpose of occupying, even if only for a drop-stone.
- Clorp [singular and plural]: TODO: who are then and what makes them tick. They are the "enemy" of the Crec. And a definition.
- club-fight: A kind of duel involving some ceremony. There is a regulatory body <why not name it here> that exists to ensure that any two clubs used in a club-fight are recognized as being "fair". The participants, on the other hand vary widely. The last rule of club-fight, as it is the most important, is: Someone's got to not be able to walk away.
- Crec [singular and plural]: The Forest to which the Zog clan both lives and belongs. "Crec" can refer to the Forest or the people who live there.
- drop-stone: A unit of time; about as long as it takes for a stone to hit the ground when dropped from an outstretched hand, on more or less level ground. They're as tall as you and used to inhibit the same planet. It works out to be a bit over half a second.
- elders-quorum: This is a sort of "The Senate" of a Forest (in cases where they have bothered). It's just as inept and entertaining as our analogs (diet, soviet, merikin, parliament, kremlin, house, neighborhood gang...)
- Ender-Of-All-Questions: God. Just one, like you. You will encounter references to "the gods". Rather improbably, this is used exactly as a modern, cynical teenager might use it: ironically. As in, /You are still such a tiresome superstitious moron that you probably believe in/ multiple /gods like back in primitive times./
- father-brother: Your father's brother. Your "uncle", but with more information.
- food-clay: Shit
- force: Strain.
- Forest-Deer: A political party (same deal) that composes exactly 50% of the Elders-Quorum (You should now be asking if these are the good guys.)
- Forest: The largest organizing category of people, analogous to a nation.
- juff: An alcoholic beverage made from fermented coconut flesh, and a polite quantity of spit from a special, designated virgin baby-maker, who is chosen yearly as the designated provider of spit (A custom that has been known to ruin some plans.)
- jump-scare: Living in something like a giant ant hill, opportunities to e.g. hide around the corner and scare the food-clay out of someone abound. This is that.
- man: A unit of measure with an obvious reference object. If you just assumed "six feet", you would be within 0.4%, just by "coincidence". Like all units of measure, but especially with 'length', the Crec are fastidious and follow a badger's warren of different ideas to further add precision. In conversation, like us, units of measure are imprecise. And unavoidably, things like time its daughter units, like speed are tricker, but there are always a few learned men to lower the precision bar ever more. BTW, it is never "men". As a unit of measure: one man, two man, three man.
- mouse-spawn: Exactly 500. The term comes from the number of mice believed to result from putting one mating pair of mice in an unoccupied one-family cave in the course of four moons. Which is also roughly the amount of time required to make the Unkempt-Loud-Suffering Pilgrimage from The Forest of Crec and back.
- palm: A unit of time. It also has two meanings with reference to distance/length.
- predict-tool: Probably a good start on the idea of "a hypothesis".
- quiet-one: A small, quiet, demure baby-maker between 7 and 11 years old. This term /is/ specific to that, even though it sounds like it could be generalized and understood. Girls of this demeanor and age were considered very precious, lovable, and pure. This is the phase in a baby-maker's life that is considered good for /molding/ by encouraging innocence, purity, during this stage when it becomes more susceptible to feedback.
- relax-marks: Everyone sits on rocks. Some rocks get a lot of mileage. Inevitably there are brown, burnished areas that repel liquids well and indicate a sweet rock to sit on. So there is some tension: On the one hand they are a mark of shame, sloth and bad housekeeping, but on the other hand everyone likes a good sit.
- rhino-calf: It means literally that but is also a term of endearment that you can still say without being too creepy. Like "dear".
- rhino-scat: Mostly known as being the name of a certain hill that was central to the events of The Battle of the Snake Meal during The Great Club War. Actual rhino scat has a certain look. The famous hill has that same look.
- rock-stick: Referring to the cavemen sex organs, it has a slightly less "rude" sense than do other profanities. It's equivalent to the modern (circa 2021) English "weener" or "peener" or "willy" or "pee-pee" or "jiggly bits" or "hookie" or "wee-wee" or "peter".
- several-finger: A quantity of something. It is exactly 10. The number of fingers you have. Like "dozen" but two less.
- sit-ham-stone: Chair
- sit-ham: Butt-cheek
- snake-meal: A "bump", "lump", "protuberance", "hump", or area of fattening. Also used in the way we say, "love handles".
- soot-pallet: Wherever fire has deposited soot on an area of stone that has been used for writing, if you write in it, it becomes a "soot-pallet". It's as common as and thought of like billboards, but are not thought of as owned, so it's acceptable for someone to write something (proper) on such a sooted stone surface. Trespassing is still a thing, though.
- squirrel-hoard: An abstract quantity meaning "a lot", if you thought "a whole bunch of" you'd be close.
- strength: "Force", in the way used in physics.
- take-money: Shorthand for take-part-money. Take-money also means "robbery" or "mugging", but the Crec universally do not make the connection.
- take-part-money: A tax.
- value-stone: A unique, hopefully big, visually appealing gem or mineral (there are many sources.) They are the currency, but their relative value is determined at haggling time, which makes for double the arguments.
- Wolf-Sleep: To meditate peacefully by actively observing all of one's sensory input, minus vision. Learning to actively monitor every inch of your skin, every sound you hear, perhaps the taste of a recent meal, one can paradoxically become quite calm and contented. Importantly, one does not "analize" the input. This leads to the kind of /thinking/ that is to be quieted. This is called Wolf-Sleep, because once the trick is mastered, practitioners, always observing their breath, from thoat outward, would be able to jump into this relaxed, serene state with ever more ease, which reliably made their third, fourth of fifth breath a big, relaxed, satisfying, full-body "hmuffffffff...." that observers of wolves and modern dog owners are familiar with. The most elite practitioners, those who understood this as more than just a way to relax, were able to endure most any sensation with genuine enjoyment, so long as it did not pose a threat. For example, a raw, bloody scrape on your leg will be crawling with gnats and flies in a matter of minutes. While this /is/ a kind of threat, and the Crec know it, one only needs to rinse the wound in a clean river and scrub it with light sand from time to time. Knowing that this sensation is no real threat it goes right to the "observe" category; not dwell upon, or worry aboout, just "observe", like all other input. These many hundred legs provided an enormous amount of "input" for the skilled wolf-sleeper to make a practice of trying to absorb ever more detail about this bit of sensory input. Some claimed to be able to note every bug's footfall and every prodding with mouth-parts; knowing usually which direction any of his visitors might be facing.
- Workers: The "Workers" describe normal people doing normal things. They are distinguished from others only in that they 'sense they are part of something'. They're OK. They're surly but unsure of themselves. They become agreeable and polite when there is talk of any kind of increase in their pay. Grav thinks these people could just choose to focus on other things.

* Ordinal (and not so ordinal) Directions

- morning-sun-left-side: North
- morning-sun: East
- morning-sun-back-side: West
- morning-sun-right-side: South

- morning-sun-left-back-side: North West (etc...)

* Numbers and Reckoning

** Whole Numbers

- all-finger: 10
- boulder-door: 100
- mouse-spawn: 500
- squirrel-hoard: "a bunch", "a lot"

** Negative Numbers (and friends)

No such luck.

** Fractions

Fractions are sounded out by the Crec in a logical way that would to us seem overly-wordy. An attempt is made to preserve this post-translation because it gives modern readers a better sense of how the Crec see abstract numbers as novel and worthy of slowing down for.

*** Examples

- one and one half of one --> 1 + 1/2
- two and two thirds of one --> 2 + 2/3
- three and four fifths of one -- 3 + 4/5
- N and X Ys of one --> N + X/Y

** Abstract Ratios

When not referring to a portion of a "thing" but instead referring to an abstract ratio (say the rate of climb of a bird or the slope of a hill), the Crec just plug in the word "part" for the abstract quantity unit that gets canceled out (which they mostly have observed). Half of a rock and a 100%[fn:: For the unfamiliar, this is a 45-degree grade, which goes to show.] grade are two things that do not directly relate, according their way of thought.

*** Examples

- one part of four --> 1:4
- one part down for each one half of one boulder-door part over --> 1:50
- one part up for each one half of one boulder-door part over --> 1:50[fn:: In a way 'up' verses 'down' is also irrelevant as either way, the meaning is usually obvious from context.]

** Angles

Angles are thought of by the Crec as simply a fraction of a whole circle. And again, the connection to related concepts like "portion of something" or "how steep?" are to them still out of reach, although practitioners of Foundational-Nature-Reckoning[fn:: Mathematics] are closing in.

In fact, the Crec quite literally are thinking "a part of a circle", the way to cut the circle being obvious to them.

*** Examples

- one quarter of one circle: 90-deg
- one twentieth of one circle: 18-deg
- two of one circle: 720-deg (which they might say to mean "I turned around twice")

** Time

- [sun-]palm: About 38 minutes. The amount of time it takes for the sun to pass the width of one palm at arm's length. For example, if you want to know what-in-the-morning it is, hold your right arm out straight, rotate your upturned hand counter clockwise 90 degrees so that your fingers are pointing to your left, the distance from top of your hand (the outer [upper-most] part of the first knuckle of the pinkie) to the bottom of your hand (the outer [lower-most] part of the first knuckle of your index finger) is the unit you use to measure the hight of the son. A Crec will say, "It's 7 palm after dawn, get a move on!"
- drop-stone: Just over 0.5s [a 5ft drop in a vacuum with standard gravity is 0.5575s]
- moon: (lunar) month [around 29.5 days]
- sun: day
- year: year

** Mass

- gourd: about one pound

** Volume

- gourd: about half a liter

** Length/Distance

- bowstring-finger-knuckle: about 2cm (the distance from the tip of an average adult male's index finger to the first knuckle)
- drop-stone: 189 meters (approximately 100 man) -- the distance /sound/ travels in one drop-stone (just over half a second). This sounds like a preposterous concept for a caveman's reckoning of distance. It is not! The idea is very simple: One person makes a **sound** whose occurrence is obvious **visually**; for example, hitting a large skin drum with a large, conspicuous [drum]stick. The drum can be heard literally for miles. One can see the drummer /striking/ the drum, for a very long way on flat, level ground [as will be the case for this procedure, usually]. Another person will adjust their distance, by gradually backing away, such that, if the a stone is dropped from shoulder-hight when the drum beat is /seen/ and hits the ground when the sound arrives, the two cavepersons can be said to be "one drop-stone away from each other. Adoption of this was slow, as it was difficult to convince the average caveperson that sound travels at a /constant/ speed (obviously!) In modern visual arts, the clapperboard has a similar function.
- man: about 6 feet ("you?")
- palm (1): The distance one /walks/ in a single palm (of time) -- about two miles.
- palm (2): The width of the palm. From one outer side of a flat hand to the other, not including the thumb. About 0.5 pinkie-thumb.
- pinkie-thumb: Stretch the tips of your thumb and pinkie as far apart as you can; that's a pinkie-thumb. It's about two palm (the short version).

** Speed

The Crec will try to decipher any "distance per time" units given, with varying degrees of struggle, just as you might if someone quoted speed to you in say "ångstrom per millennium" or "centimeters per year". There's no judgment about this among the Crec. They are always thinking of the best combination to express an idea. As their units of time are few and imprecise, there are correspondingly fewer combinations to use for speed and the appropriate choice is usually obvious. Man-per-dropstone and man-per-palm are popular combinations. Most often, a familiar analog will be used: as fast as a saber-tooth tiger.
