#+title: Spoilers
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="index.css" />
#+OPTIONS: num:nil

Hebbo!

Here be spoilers.

 Outline

Everything is subject to change, eebureetang. But you'll have to retitle if we don't have a smackdown involving Gog's use of the word "boulder-stump" somehow.

** Ch. 000 Preface

We meet the Crec and learn about their world. Verk tells a story. It is deeply meaningful for some.

** Ch. 001, wherein we learn of Zog's great acumen and fertility

We take the reader back to Zog's early years. Zog current clan leader, and that's why it's called "The Zog clan". Zog was a hero's hero, in other words, lucky he's not dead. He was known for his daring and just kind of /falling into/ situations that make him have the appearance of a total badass. He just happens to be the guy in the good -vs evil movie that throws the rock that seriously wounds the bad guy in the satisfying end. Roll credits. But despite all of his impressive doings, he really only has so much of a clue what's going on. He's not learned to have a look of wonderment when things work out for him. Giving the impression that he meant to do that all along is central to his persona. This means giving some pretty weak and convoluted explanations. We hear the perplexing story of Zog's first dive, and as far as anyone knew, first dive ever in the tar pits. He came off looking like a total stud, but came within seconds of dying about eight different times in the process.

Let's have a from-birth to marriage fast-forward, followed by tales of daring from his youth. And of course, displaying, entirely for what it is, his deeply held, more or less random believes that he's willing to club-fight over. Lots of adventures. Lots of badassery.

The lesson? There is a right way to be a Crec. Zog simply exemplifies it.

** Ch. 001, wh


** Ch. 00~, wherein Grav starts studying to become a lawyer (though we have a clever name for it)
...
Note: Grav cleverly invents the concept of "lawyer", works hard to become one, folks realize that not just anyone should be allowed to be a lawyer as you can ruin people's lives (!) and so creates Official Criteria, which Grav cannot meet. Grav becomes the first lawyer to exist and then the first law school student to fail the Bar (what funny word instead of "bar"? "stick"?) exam.
...
** Ch. 00~, wherein Gog scratches "boulder-stump" into a soot-pallet and shouts it from atop Lame-Monkey Mountain three times on a dare
...
** Ch. 00~, wherein the Make-Stop-Banana-Word Commission of the Elders-Quarum begins proceedings to update the list
...
** Ch. 00~, wherein Zog distracts from the business of the Elders-Quarum with an incident involving a hyena
...


* Bugs

- Verk's joke on Lu makes no sense with the level of sophistication they have. Even if you say "well, after the club wars they had a big Renaissance thing", the hide they share with Oh-Mas is clearly sophisticated, but also way before Crec times BUT the Momma Bear Palace (or whatever) is obviously wicked grand, and yet they did not know to /tie a rope to a boulder and yank it out of the way/?
- It seems like Grav "retires to his burrow" a few too many times, probably creating an inconsistency.
- Thag gives a big speech, but he has no lower lip!? Maybe he has a speaker. Maybe we lose track of who is the main attraction: the speaker or the deformed, dumb man? (oooh)
- It seems like we claim G&G and all cavemen always run in the woods (first, maybe drop that?) but sometimes they are walking!!? Actual bushmen (whatever) do not do this unless they're running down a prey. Maybe instead, the men are in a hurry to get to the mine for some /reason/...? Then they may freely walk on occasion, released from the author's unreasonable expectations.
- wrt running to the mine, maybe you issekinichou: you explain /why/ they are going (which we don't) and that is an "mild emergency" of some kind and so that is also why they are /running/.
- Lots of references to forest-children. It needs to be presented in-order.
- How do we not duplicate definitions: one definition is in a footnote, the other is in the "Glossary"?

* Relations

- Grut[fn:: The Great.], haver of potent seed, starter of epochs. "Son Of..?", you ask? Well we don't know the answer to that, do we. His time is as far back as memory goes. He and his only wife Jaar are the founders of what is /now/ called the Zog clan.
- Would like too mechanize this and make a pretty diagram, maybe a python script.

* Notes

- Modern humans fear death in the same way the Crec fear a painful or horror-filled death.
- Wouldn't it be cool if Jurd had some "audio problems" and Thag had to struggle out there in front of hundreds of kids silently for a quarter palm.
- If we need a girlfriend episode: We know that one just ignores women on selection-journey, but a character /could/ choose to break protocol, fall in love, and escape into the anonymous jungle with your new bride-prize to start a new life. aww.
- Seems like if G&G are going /to/ the camp from BZ, it would be reasonable to assume that Verk came /from/ that direction in Ch01. So, do G&G not go through monkey pass?
- Snogny-Dodk copy protection:
  - Some scheme has a laughable workaround
  - He works on getting "the authorities" to prevent "theft"
- G&G realize that any kind of "penalty" for anything has to be anchored by another "penalty". The first three steps might be a "fine", the fourth "torture", the fifth, "death"... but all must be anchored with death. Force is inevitable. something!! <-xxx
- A ridiculously huge flag could fly atop Bhorv Zolk (on occasion, for reason)
- There are a couple of colourfoul characters that could exist:
  - "hi"
- Are there airquotes in Crec-world?
- Naming surrounding the rock-stick-rocks:
  - The three pieces share a single name. There is no name for the rock-weener by itself or the halves.
  - It is known to all as Ender's-Sword.
  - G&G call it Ender's-Stump but only amongst themselves.
  - G&G have their own name, which they share with nobody. They got tired of making finger quotes.
- Notes about military:
  - We need a good name for the camp: "Choh-Ov is an xxx"
  - Towns around military bases are universally a disaster (as they are in Reality, along with University towns) The following name choices were made to make it easier to remember (For me! We should probably do some Okinawa bases.)
    - Fayt-Caves ==> Fayetteville
    - Choh-Ov ==> Fort Bragg (get it?)
- We eventually find that you can say "BS" in place of "Boulder-Stump" and for some reason be totally OK (long explanation of translator's choices when terming it "BS".)
- It would be awesome if when Verk kicks it, they find a great big tumor (heh. maybe he falls off a cliff and this grey turd comes oozing out of his skull amidst his brains. The Crec know, "this ain't right"). Knowing "this ain't right", they ponder the possibility that this might have been a/the /cause/ for all the fun Verk features.
- Self Marriage ceremony (no, this is not "gay"): The Crec have a Self-Marriage ceremony, where the caveboy-coming-of-age takes a bunch of wedding vows about loving himself no matter what. Nobody laughs, a few ol' gits cry. This among men is considered waaay more important than the other kinds of marriage. It is here where we revisit some of Grav's delightful encounters with Verk.
- It turns out Zog is a really good dude. His son, Grav think's he's pretty awesome except for one quirk: He defends Brother Verk no matter what and is willfully blind to any amount of evidence.
- Verk has a son named XXX (actually, that'd be a pretty good name). He is clearly dramatized by having Verk as a dad and just runs out the clock doing some (sometimes shockingly) cool stuff. Fiddles with this and that, stays out of Verk's way, is quietly an unobtrusive genius occasionally. Is deferential to the point of nausea. Don't want no trouble. Talks very little.
- Someone speculates that the outer perimiter crack of the stick-stone/devil-fish-stone is so sharp because the outside had been polished by Nature. Otherwise it would be jagged. Reproducible of course.
- Capitalization of Workers explained: they got together, decided to spring the union thing on G&G, who were more than prepared. The workers would shout, "THE WORKERS!" at the end of every other utterance (but only when appearing as a group) and so after literally hours of negotiation, the compromised on having their so-called superiors refer to them as a group in the same way: No matter in what context, when refering to the workers, according to the bylaws of G&G, had to make an effort to enthusiastically shout, e.g. "Hey, Guff, some of /THE WORKERS/ are late this dawn. Do you know of any reason?" All were satisfied with the arrangement.
- The reason they keep fucking up on standardizing certain measurements is that they literally have not yet thought of the possibility of these things varying. Crec were Crec.
- At some point, the sluice encounters a low cliff on the riverbank. They find /booones/!
- Mmaybe something so valuable is found that we have to start worrying about theft at the mine.
- Some one gets trapped in the River-Fist. You just get pushed down there and twist and twist and twist along with a bunch of rocks. The only salvation is either to move the sluce (maybe it's wedged in place for some reason) or to install the "boar", which the Workers, in their panic, drop over the side, 8 men (or something) down below. Oh! Noes!
- Numbers are wordy in order to put us in a frame of mind where abstract numbers are "novel", as they are to them.
- Somebody notices that if you twist three fibers one way and wound them the /other/ way, you'd have some twist-vine that is not bouncy and doesn't twist when it's not supposed to.
- There needs to be Ernest. T. Bass/Leroy Jenkins character that is nice-junlge-term-for-crazy and injects harmless randomness all the time.
- Now is your chance: invent an animal that, instead of giving birth, lets its babies gradually it it from the inside out, hunting for food until it becomes impossible, then drops dead and is eaten some more. Then something furry, adorable, and covered with rotted gore climbs out.
- "Now, Gak, you've got a situation here with that boy of yours. He's mostly just runnin' around messin' with his stick and hanging out with girls. See, if he was an all-finger or more, that'd be good news for you, 'grandpa', but sometimes it's just unseemly. I saw him smelling a quiet-one's pile. Time was, you could drown a wretched runt like that in the river with a good hemp basket and a rock. The do-gooder Forest-Deer and there meddlin in family life put an end to that! But..."
- I like the expression "thou dost smite meeee!"[fn:: Notice, not a question like 'why...?', this is The-Ender you are talking to.] as a ritual kind of thing that's as unconscious as "Allahu Akbar" or "Bless You". But screamed at the sky during the hight of frustration, of course. Sometimes, as the "eeeeeeeee" is lengthened, the frustration goes vertical, as someone is high up a tree wrenching on a beehive. Usually, this last jerk of rage-derived power is enough to at least "unstick" the frustrating situation (You might imagine the beehive coming loose and the caveman falling 4 stories onto packed mud, the last 'eeee...' trails off as he lays in his crater.)
- The word "think-long" is the transliteration of the compound word of theirs tha means "rational" in pretty much the sense that we mean it. It is a slur because, while it has been observed that rational thought bears good results often, the overwhelming majority of data showed that, when your life depends on it, as it nearly always does, relying on the supernatural bears better results. Therefore, being think-long (rational) is to just waste time and look like a good, naive target for pouncing instead of learning and practicing The Art that would likely save your life one day. rational: insult.
- The big reveal at the end: bad 'bad' guys and 'good' guys literally just go their separate ways.
- ZoMG, drugs! The Forest abounds with drugs. All the bluehairs (and everyone?) take some brain-melting psychedelic (thing), which is considered wholesome and old-fashioned. It's both their sacrament wine and their cut loose on Friday wine. No big deal, old Uncle Elmer is talking to future alien trolls, just like in the good old days. Pretty much everything else is devil weed, but G&G are bold, fit psychonauts and experience trips that would be considered trips from the perspective of fuddy-duddy trips. Importantly, when they meet up with the girls, there are lots of drugs and of course monkey-business (oh, that's good. let's make that just mean "fucking" and there can be a polite word for "baby-making" ...)
- The Helpful Monkey is a river that flows towards morning-sun-right-side towards Bhorv Zolk. Its start is the confluence of an eastern branch, The Lame Rhino [tigris], and a western branch, The Great Meal Stone [Euphrates]. All together they make a Y with the bottom, virtical part pointing southwards to at Bhorv Zolk. Yes, you can look at a map of the fertile crescent. This is all just for ease-of-recall and rough geographical reckoning.
- [nope! we have flowering plants. we /need/ flowering plants.] I said "pre flowering plants", didn't I? 1) this probably impossible [maybe who cares], 2) "banana", "melon", "gourd"...will have to rethink. All this because I wanted to use "uvula" instead of "pea"?
- Brother -> Bro is purposely propagated among the Crec. Soon cave/men/ are calling each other "bro". Then there is a great buggery scandal in "the military" during which, from one of their discussions, comes the hilarious idea of "bro-ham: a male buttocks used as a substitute for cavewomen (we need a good word for 'vag')" As in, "Out on deployment and away from your wives for moons at a time? Worry not! bro-ham abound."
- The mysterious forest babes: G&G, on one of their especially distant and daring excursions, near the border with xxx yet-anther-another-another-hated-neighboring-Forest xxx. They are sinewy, flexible, and fit. And they don't sweat much. They are giggly and have absolutely no overlapping language with G&G but they somehow manage to find a way to agree to meet back at this very spot (don't forget) exactly these many moons from now (don't forget or miscalculate). And they have fun. Bouncy-bouncy. They are like a bizzaro G&G, but baby-makers (although in literal terms, G&G thought of babies very little). They were ingenious and mysterious like G&G. They thought freely (oh so freely). And loved a bit of mischief of any kind.
- Needs uniformity, rules, standardization:
  - Capitalization of Crecspeak
  - The language used to express numbers.
  - If we are going to "tag" Crecspeak, should be done soon.
  - I flop back and forth between "men" and "cavemen", etc. do I care? do I have a rule? am I making a point with the choices?
- It would be neat if there were lots of stories about "small-ones" (frickin babies), met at random in unimaginably distant parts of the xxxworldxxx. They don't speak. They don't act surprised. They trod on with purpose, armed like a skilled, adult hunter, look your way and nod, but never say a word and move on. These are known as forest-babies (maybe) and are fucking mystical.
- Communication
  - Loud, long-distance whistling.
  - Somehow making a single loud bang. And then having a code "one bangith mean trouble, two bangith mean party"
- The shouting of "boulder-stump!" is something Gog did in his youth. The search for the culprit had been at least "active" until the present day.
- Don't ever forget to make the good guys bad. There should be lots of people "signaling" who are Forest-Deer die-hards and act hella retarded. The reader should be utterly unable to decide who the good guys are.
- There must be lots and lots of "public works" of every kind. We let the Elders-Quarum decide how to spend N% or our money and then get outraged when it's not used "correctly". Rocks, clubs, clubs with sharp sticks in them...
- Everyone is a caveperson. It's as appropriate to say "cavelady" as it is to say "lady".
- The feeling is light and easy like a mockumentary. The narrator is just "me", so I don't have to remember what "voice" I'm using.
- No humorous-fake-terms for things that /they/ have and /we/ have a name for. For example, no need to call a tree a "massive-weed" or to call a cat a "gerbil-dog". Or maybe yes do that. It would be pretty sweet if Crecspeak words got a special tag so we can identify, use special fonts, check for glossary leaks...
- Definitely have a "global warning" analog
- Someone gets caught using the "bachelor-tree" and is vaguely shamed for it the rest of their life.
- We need to get around to: Gog said "boulder-stump" and is tried for obscenity and has Grav as his lawyer.
- Somewhere here and there we need to throw in a "very special" episode where someone get's gorily torn apart or beaten to death or thrown off a mountain for something that totally deserves it: man-on-man buttfucking, conning granny, child-diddling, disrespecting the Chief... Really shock it to 'em.
- Is there a character that's always trying to make a flying machine and fails over and over in hilarious ways. Is there?!
- There needs to be a skill or activity that makes a caveperson really look like a badass. Like taming a hyena and riding on its back (which works out usually.) And a regulatory body that ensures that only the properly skilled are allowed to operate a hyena. Lots and lots of tests, criteria, and note scratching. They should probably have to wear some kind of coconut helmet, by law. And polished amber sunglasses: Crec-Bans.
- The lizard-bird (always?) hunts at night because it his infra-red /pits/, like you-know-who.
- Thag:
  - Is kind of helpless and losing control of his posse.
  - Because he needs to use so many click-clock words, he sometimes chooses "the closest thing", constrained by sounds he can't make. That plus homonyms and other zany linguistic hi-jinks, make for many a falling prat.

* Ephemeral Notes

- We use Under-Men to both mean "verk's thugs" and "the learned men in the ancient-speak burrow"... must untangle.
- Lizard-bird account: it/he used variously. "she"?
- Could/should Verk meet up with G&G on their travels to/from clubbing?
- Some places to keep up with:
  - J'anz-Caves: Where Thag was walking FROM
  - Hummingbird Pass the road Thag was traveling along, kind of a Balrag border-road.
  - Prominence-Caves: Where Thag was walking TO (he lives/lived there?). [Is it on Water?? Do we have a sea down there??

* Bigger Spoilers

- It might turn out that Lansh is a double or even a /triple/ agent.
