#+title: Bird
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../index.css" />
#+OPTIONS: num:nil

Grav and Gog were faced with spending the night, baring a miracle, in the most dangerous place possible, only because a much greater danger had recently moved into the area, like bad weather, but worse.

This was part of the life-long education the men had about lizard-birds.  The woods were safer but not safe. They were also the only reasonable choice.

This was definitely toward the end of the curriculum, but they both knew the approximate odds of either choice, and chose the least bad: They would be spending the night on the edge of Small Woods somehow or other.

The forest-child stood and stared at the two, both lost in thought.

He made the eyes-widening, brow-rising, cock to the head "/well?!/" expression that all humans know.

"He seems to be 'asking' us.", said Gog.

"Yes.", agreed Gog. Then after a pause, "What is he asking us?"

The forest-child made a mock jog in the direction he had been heading and then again: "/well?/"

Grav and Gog looked at each other. Not having a preference for /where/ along the margin of the dangerous woods they would sleep, at least generally, they gave in and mimed that they would go with him. "After you, sir", was their chosen gesture of response.

They followed the stinking baby at a right angle to the trail. As mentioned, forest-children tend to travel as though everywhere was a path. They could travel the path of a bird, but projected onto the ground. For them, the shortest path between two points was shorter than it is for most.

In the growth strata of most jungle or woods, there was a fairly consistently unoccupied bit of vertical real estate.

There were juicy, mostly edible ferns and broad-leafed weeds up to about a pinkie-thumb from the floor. The next-tallest "layer" was probably about nipple-hight for an adult Crec.

But a /baby/ could trek along unbothered by anything other than what for /him/ would be light knee-high, dewy, soft green leaves, with the next layer of green being, again for him, one or two heads above, which is a good thing as this is also a strata where spines and poisons were in wider use, to shoo away anything that might disturb their peaceful plant-life.

For the men, this meant a walk through thick, chest-high bush that was all painful or uncomfortable in some way or other. In addition to the irritable plant life, not a few cantankerously deadly fauna lived in this layer too. This was the whole reason for established paths after all!

A Crec ecology text book could easily have used a picture of this bit of woods to illustrate these concepts.

The men, their spears now being employed as brush clearing blades, at which they were barely more useful than any other stick, were swatting away face-sized, muscular, quick spiders, all-but-invisible small, but poisonous green vipers, and the occasional poisonous frog or centipede (and the pretenders of each, who they could immediately identify as harmless, even at this pace, and would try not to wantonly kill.)

Bringing a spearhead down flat and sharply on top of some of the bigger spiders would make an audible "pop" with spray spider guts. The two men would sometimes try to get the other with a good spray of spider guts with an expertly angled swat of the spearhead[fn:: In the modern game of golf, this is known as a 'chip'.]. It was a kind of game they had.

It occurred to them both that if they were the size of a baby, they too would do as forest-children do. They could both see that the baby was having no trouble at all. He was currently dragging his long spear behind him, his hand around its tip, his thumb checking the point for sharpness at intervals[fn:: This is a nervous habit that is frowned upon by the Crec. They call it 'worrying your point' and it's used metaphorically to mean 'getting worked up over nothing'. This /will/ dull a fire-hardened spear point on the scale of days.].

Though he had a mostly normal speaking voice, if a bit high-pitched, his singing brought out more usual-sounding baby noises. He was singing softly in his language, presumably, punctuated with rhythmic coos, mummers, and occasionally a delighted squeal. This did nothing to take away from the uncanniness of this swaggering baby.

It was getting dark, but was not yet killing-palm. The forest-child seemed unbothered, and was now making occasional tight turns, as though the party had switched to surface streets and was almost home. There seemed to be a /destination/ coming up.

Revealed slowly as they rounded a larger low tree, they could see a sort of hide that was clearly not Natural but was just as clearly very old. It was made out of stone that had been squared off mostly <-xxx. Where it was irregular, it appeared more that this was due to erosion of some kind. One could imagine it being /quite/ square in the past. It had a look that the men would both have described as "Unnatural"[fn:: This had a distinctly positive connotation. It had the sense of 'made by skilled cavepeople for utility and comfort.'].

The fine but irregular joints between the stones gave the impression that the creators had balanced finding appropriately-shaped stones with the trouble of removing material to create a finer fit. The joints between the stones did not make a regular, geometric pattern like one would see in modern block construction. The lines between the stones were more jagged and irregular, but in a pleasing way.

In this case though, where there were joints they were impossibly tight. There was the look of crazed lines scratched all over a smooth rock wall, for the exterior of the hide had proper "walls", at right angles to one another. It was made from irregular stone puzzle pieces that somehow fit one another perfectly.

The Crec did not have a word for this shape. It was a nearly perfect cube.

xxx should be way off the path if they didn't even know about it xxx

As the front of the hide came into view, they could see that some rather sophisticated modern construction had been done too: There was a sort of wood entrance-way constructed around the opening. The stone was clearly many rotting-ages[fn:: A 'rotting-age' is reckoned to be the time required for a fallen tree to rot completely back into soil. The Crec knew this was an imprecise unit of time. Part of the point was: It's such a long time, that one needn't nit-pick about whether the tree was "fully rotted" by this point or the other. We might say 'eons'.] old. The wood was comparatively new.

It was not a particularly inviting entrance. This structure was solely for the purpose of protecting the occupants.

There was a low, two man long sort of arched hallway made from woven and somewhat living vine. The walls of this tunnel were lined with dozens of sharpened, springy saplings all anchored at their base to the wall, hanging at lazy angles near the wall and all pointing outward.

This is a contrivance that the men were familiar with. Something like this was used sometimes to protect the opening of a cave from anything big enough to be a threat to humans.

Looking inward, one's eyes were met with a bunch <-xxx of fire-hardened spikes, making entrance impossible for a crazed, hungry predator but still allowing a human to patiently move spikes out of the way, using arms and legs to retain the ones already past, going slow and patiently. A human could get in with some strategy and patience. Nothing dumber could make it through, generally.

This was referred to in standard Crecspeak as a spike-guard. It was known to Grav and Gog as a "porcupine-pussy"[fn:: They thought this much more descriptive and poetic.].

A typically Crec spike-guard had all sorts of clever latches and vine catches that would make getting /in/ much easier than it was in this case, where they were both struggling, helping one another with a stab here or a smack there, from a poorly timed release of a branch bent out of the way.

The baby gave them exasperated but patient looks as he stopped repeatedly to press back some of the more troublesome spears at their base and wait for the two enormous people to ease past all their "pain points".

This was a hide that the forest-child somehow knew about in advance. The plains were not an option this evening, as the forest-child's message was ultimately pretty clear: There was a lizard-bird, hunting at night, which was the usual, and along the nearby plains[fn:: Which was also usual for a lizard-bird, though they were so rare as daily experiences go they hadn't really anticipated this particular problem, really. Caveman Thag would have been disappointed.].

And the hide was a perfect solution. They would likely just enjoy a night of periodic but contained terror as they get sniffed out and then mercilessly charged by an animal that gets bloodier and angrier with every failure. All three having spears, they might even possibly enjoy the pleasure of mortally wounding a tooth-cat with a satisfying stab down its throat[fn:: Tooth-cats were /hated/ among the Crec. Tooth-cats were for them what wolves are for modern sheep farming settlers. There was a mindless hatred. They would see no downside to all-out extension. Every Crec was at most two or three relations away from someone who had been killed and eaten by a tooth-cat.].

For them it would be a kind of entertainment.

They both noted how some of the living vine of the portico was grown soundly into the stone of the hide. Anything that wanted in, short of an ambling-feast, would need to use the door, which was well protected, as described.

They looked around as best they could in the dark hide. Gog was rustling through his kit, trying to get the ingredients necessary for light.

Soon Gog was making a noise and a sight that instantly got the attention of the other two. In the complete dark of the hide there was a bright flash accompanied by a click. Then another. Under normal circumstances Grav would be taunting Gog about his fire-making skills, but this time he was wishing him nothing but quick success.

After all-finger or so clicks, there was a blue flash and then a growing flame of warm yellow.

Gog was holding an unfired clay oil lamp with a small, bright, efficient flame at the tip of its sturdy, short nozzle.

This is a kind of travel lamp carried in nearly all kits. Though porous, the outside was waterproofed to the degree possible with pine pitch fixed with a packed layer of soot. This gave the outer surface an asphalt kind of finish that was good for the trail. It was thick enough to provide some impact protection, which is a big concern for the fragile things you drag around the jungle with you always. And to whatever extent the pitch soaked into the lamp, it was only so much more fuel. Old lamps gave of a distinct comforting smell; grandma, warm fires, salad days.

For fuel you could of course use any one of literally thousands of known flammable oils. One's preferred oil usually came down to which unpleasant characteristics could be endured for the price. Oil was pretty expensive. Wherever you got it, the person you got it from got it in the same way you yourself could have. Your time was worth what his was. So you generally considered the cost of most things, including flame-oils to be about what you'd pay yourself to go out and get some. A lot, in other words. But that value could be obtained in completely different ways: Maybe you're a modern stock broker. Maybe you mine gems with your bare hands.

Of course they had the nicest oil. It also happened to be rather a cheap one as luck would have it. Most considered its smell to be a down side. They thought just the opposite. The lightly refined turpentine[fn:: More or less.] they preferred burned predictably, gave little smoke, had a bright, well-colored flame, and smelled to them like an exhausting day productively working with lumber. It was a nice, crafty kind of smell.

The worst part of the night, they were sure, was going to be sharing a small burrow with a reeking baby who also happened to be a very poor conversationalist.

In the cheerful glow[fn:: For that is what it was.] of the lamp, the two men scanned the walls for anything bit-y. There was an especially hideous land-crab[fn:: Crec knew plenty about crabs. They were 'exotic' this far away from any source, but they knew well the body plan, the innards, and the delightful /taste/ of crab. The shells were always kept around for some user or other. All you needed was a rich uncle willing to let you sift through his garbage. Being familiar, somewhere far back in the Crecspeak family tree, someone noticed that this spider, the variety they shared the hide with, looked very much like a crab, had a lot of the same kinds of spines, made a similar clicking when crawling along rock, and provided an almost identical eating experience to their "delicacy" cousins. They were more plentiful, but tasted distinctly worse than actual crab, so it was more "just a name" except to the very hungry. And they were harmless. Huge, but harmless. And also slow and shy until startled.]. A few millipedes that one would not want to touch[fn:: Nothing capable of spraying.].

And right in the middle was a pile of burnt bones and cold coals.

Having gotten snugly into their hide-burrow and it now being properly dark, as best they could tell in the dark wood, Grav and Gog talked at length about their predicament and plans.

For one, they would have to awake and get running dangerously early in order too beat conch. They would get docked by xxx for not having shaved[fn:: xx] and not wearing their rhino-calf chest armor[fn:: xxx].

The last palm of woods would not be entirely quiet at that time. Missing conch was punishable[fn:: xxx] and they were balancing the penalty for that with the reckoned odds of getting eaten by one thing or another along the way.

It was not unusual for a lizard-bird to continue its hunt until early morning, even after dawn. The men did have clear skies and a sliver of morning-moon in their favor.

/Play it by ear; we're safe for now/ was the unspoken conclusion. There was nothing tangabile the could do about the future at this point.

Grav and Gog's attention went back to the forest-baby.

They had determined as best they could that his name was Oh-Mas, although Grav wondered if /one's name/ meant the same thing to the baby as it did to them.

He had an idea that, /yes/, they had names, /of a sort/, but /it was complicated/. Just as the instincts that forest-children have about language in general could be leveraged to get their attention, similarly did Oh-Mas' constant chattering give the impression that there was 'a lot going on there'.

Oh-Mas too was working with fire.

He had packed a large pipe and was lighting a twig to get things going.

There was a lot to know about the smoking of plant matter in the ancient jungle and woods.

Grav and Gog were instantly curious. There were so many plants in Nature, and so little time to experiment that those from strange parts, /even if those parts had all the same plant life/, had new discoveries to relay, and usually visa versa. It took a lot of research. In this, ancient people were experts.

He had no whole leaves that they could inspect. Grav and Gog took small pinches as specimens and stored them safely in case it turned out there was important medicinal knowledge at stake.

"Gog, I think we need to go easy. There's no judging its power from appearnces."

"Sure. We need our wits about us. Let us just calibrate ourselves by supposing it has the force of toad-root."

Grav laughed remembering how sick-monkey and randy-monkey they had become with the Balrag girls.

"Ok. Well, I will take exactly half of that and so will you."

"Agreed."

Oh-Mas had his pipe going by now and had filled the top half of the burrow with laminar green smoke. The appearance of the smoke alone would have been a warning to more experienced reflect-soul-trekkers.

Without ceremony, Gog grabbed the pipe from the baby. For an instant Oh-Mas made a very baby-like "whaa!" which he clipped sharply. His face returned to its friendly resting state and he made a pantomimed two handed "release" of the pipe with a smile, though it had already been taken from him.

Neither man ever mistook Oh-Mas for an actual baby again. This was clearly only his 'appearance'. Sometimes there was a restrained civility in the forest-child that made the men wonder if he was always in control of himself.

After watching this and then mindlessly accepting the pipe from Gog, Grav's next recollection was of staring at the ceiling.

He and Gog were laying on the floor face-up, with the tops of their heads a palm apart and each man's feet extending towards the hide's walls.

They were both staring at the ceiling. They had been in a long, convoluted conversation following some of the most inspired trains of thought he could recall when he "came to". He had been both exploring his inner mind and having a deep conversation with Gog at the same time, Gog's voice being more or less detatched and coming from nowhere. He wasn't aware nor did he really care where Gog 'was'.

The thing that brought his sick-monkey around was Oh-Mas snarling out at the opening, and more or less normal, but loud breathing from an all-finger all-finger all-finger gourd predator of some kind. Most likely a tooth-cat.

They could see the very tip of one claw slipping in and out of the vine-work nearest the stone. The mass of vine was probably three parts of four of one pinkie-thumb in thicknest at the least. The claw, whoever's claw, was at least that long.

And it belonged to an animal smart enough to start work immediately on tearing the vine trapway away from the hide altogether, which for an averaged sized male cat would mean sure death, as it could probably fit a good way into the opening and its reach was enough to at least poke enough holes in you to end you.

The gaps between the vine provied enough space for the Oh-Mas to jab it a few times pretty good, to which it audibly reacted, which is a good sign.

Grav and Gog continued to state at the ceiling.

The battle cries of the baby got intense enough to interest them and rolling their heads over to watch the show.

There would be no more talking for a while. The animal, initially just hungry was now mad with rage and sought revenge. Having glimpsed the animal that was doing all the damage the cat was also a bit disgusted with himself. /This little animal, and any friends it might have in there must die this night. No one must know of this/ the cat may have thought.

Grav and Gog could now clearly see the mad beast at the end of the tunnel, the cat taking some time to just express his anger just in front and those spikes now appearing hoplessly flimsy from this side.

Whatever the danger, the two men were captivated.

The cats fangs looked like polished tin, and seemed to be devoid of defect. The gums anchoring the fangs were not pink but blood red, almost purple. Gog felt he could /see/ how tightly those fangs were held by those gums, which seemed to be made of flexing muscle, actively holding, wielding those fangs. The symetrical tongue, tucked fark back in the throat had spikes that went from simi-transparent crystal where they were rooted in the toung to shiny black at the sharp tips, like terantula fangs.

As if in place of spume, the tiger dripped think, undiluted blood from its mouth, it had no apparent wound in its mouth, but its throat could have easily been pierced so furious and sure were Oh-Mas' jabs.

It was drooling blood and pulsing bright pink foam out of the sides of its mouth in pluses, a bit more pushed out with each breath.

More purple-pink gum would be exposed with every high screech-like roar.

It was pissed.

Crazed, the baby grabbed the only lit lamp and smartly slung it hard right onto the cat's brow, where it shattered, covering the cat with lighted pine pitch from the nearly-full lamp.

This roused the men, both of whom scrambled together in Grav's kit to get his lamp. Gog found it first and hurriedly lit some dry litter from the hide's stone floor with embers from Oh-Mas' pipe, which he set to gloaing with a few puffs of air beforehand.

With a heavier dried leaf from this he finally lit his lamp. Looking up he realized that light availability was not a problem for the time being. The cat's front half was fully alight. It had a sort of mane of standing hackles between its shoulder blades of made of fire. The liquid ran down his back and ribcage and also down the outside of its front legs, and the flame followed.

The cat spent a few drop-stone seemingly calmed by the fire. It was pacing in a circle as if thinking of lying down.

But then the cat snapped.

It charged the opening, propelling its whole body with hind legs and making syncronized swats with both fore limbs, claws extended. The cat was doing a sort of wheelie, propping up the front half of its body with accelerating rage.

It's swatting, almost clapping, but with paws not quite meeting, got more rappid as he approached[fn:: This can be seen in modern domesticated casts. It's known as 'fuck your shit up' mode.].

xxx sure seems like if cats like that walking around, no one would go outside.


So long as it stayed where it was, all was safe.

Things began to feel unsafe for the men when they looked at its eyes, 


xxx

xxx
xxx they fight off animals
xxx one gets its claws in and tries to tear away the whole "tunnel" structure.
xxx they remark repeatedly about the stink.
xxx maybe the baby has a peace pipe?
xxx   - "we should take it easy. remember last time."
xxx   - baby smokes a shitload
xxx   - maybe they smoke, the men get paralyzed with "visions", baby
xxx     fights off everything by himself. (useless big people)
xxx they "wake up" get ready to, have a tearful goodbye with their
xxx new babyfriend.
xxx
xxx they cross the plains, maybe swat off a lizard-bird.
xxx They pass Verk's palace, remark or something.
xxx
xxx They get there. Find some musty, dusty armor to throw on, ill fitting.
xxx
xxx They /just make it/ to conch, stand at attention
xxx
xxx They get taken aside by someone. "Hey, you guys found that thing right?
xxx Can you find me one?..." They are able to ditch club drill and do
xxx something cool instead.

--

Off the trails and off the plains meant /in the woods/ adjacent to Snare Plains, a place where rich biome met rich biome and all kinds of killing went on. It was, in literal terms, "between the plains and the woods"[fn:: Which of course is the Crec expression that means 'between a rock and a hard place'. 'The plains' being haunted by something like a lizard-bird in the metaphor.] This was a phrase that was bandied about, but it was no joke to be in there any more than is, say to be caught in /the undertow/.

And yet there they were. The forest-child was in-the-know about such things. There was no doubt. Lizard-bird aren't /everywhere/ in Crec. Given plenty of other factors, it took several hundred square miles to support just one. So they are rare, territorial, and deadly deadly. You might think in terms of the lizard-bird being to the Crec what great white shark is to modern humans, supposing of course that modern humans spend all their time swimming at the beach. These sky-trolling sharks were a lot less hypothetical, in other words; a lot more day-to-day. You were always right on the sky's shore, after all.
