#+title: Bird
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../index.css" />
#+OPTIONS: num:nil

Grav and Gog were faced with spending the night, baring a miracle, in the most dangerous place possible, only because a much greater danger had recently moved into the area, like bad weather, but worse.

This was part of the life-long education the men had about lizard-birds.  The woods were safer but not safe. They were also the only reasonable choice.

This was definitely toward the end of the curriculum, but they both knew the approximate odds of either choice, and chose the least bad: They would be spending the night on the edge of Small Woods somehow or other.

The forest-child stood and stared at the two, both lost in thought.

He made the eyes-widening, brow-rising, cock to the head "/well?!/" expression that all humans know.

"He seems to be 'asking' us.", said Gog.

"Yes.", agreed Gog. Then after a pause, ".../what/ is he asking us?"

The forest-child made a mock jog in the direction he had been heading and then again: "/well?/"

Grav and Gog looked at each other. Not having a preference for /where/ along the margin of the dangerous woods they would sleep, at least generally, they gave in and mimed that they would go with him. "After you, sir", was their chosen gesture of response.

They followed the stinking baby at a right angle to the trail. As mentioned, forest-children tend to travel as though everywhere was a path. They could travel the path of a bird, but projected onto the ground. For them, the shortest path between two points was shorter than it is for most.

In the growth strata of most jungle or woods, there was a fairly consistently unoccupied bit of vertical real estate. There were juicy, mostly edible ferns and broad-leafed weeds up to about a pinkie-thumb from the floor. The next-tallest "layer" was probably about nipple-hight for an adult Crec.

But a /baby/ could trek along unbothered by anything other than what for /him/ would be light knee-high, dewy, soft green leaves, with the next layer of green being, again for him, one or two heads above, which is a good thing as this is also a strata where spines and poisons where most called for to shoo away anything that might disturb their peace. <-xxx

For the men, this meant a walk through thick, chest-high bush that was all painful or uncomfortable in some way or other. Plenty of the more fauna-type dangerous and painful things lived in this layer. This was the whole reason for established paths after all!

The men, their spears now being employed as brush clearing blades, at which they were barely more useful than any other stick, were swatting away face-sized, muscular, quick spiders, all-but-invisible small but poisonous green vipers, and the occasional poisonous frog or centipede (and the pretenders, who they could identify as harmless, even at this pace.)

It occurred to them both that if they were the size of a baby, they too would do as forest-children do. They could both see that the baby, now dragging his long spear behind, his hand around its tip, his thumb seemingly checking the point for sharpness mindlessly at intervals, had no trouble at all. <-xxx

Though he had a mostly normal speaking voice, if a bit high-pitched, his singing brought out more usual-sounding baby noises. He was singing softly in his language, presumably, punctuating and making rhythmic noises made of coos, mummers, and occasionally a delighted squeal. This did nothing to take away from the uncanniness that this sophistocated baby had.

It was getting dark, but was not yet killing-palm. The forest-child seemed unbothered, and was now making occasional tight turns, as though the party had switched to surface streets and was almost home. There seemed to be a /destination/ coming up.

Revealed slowly as they rounded a larger low tree, they could see a sort of hide that was clearly not Natural but was just as clearly very old. It was made out of stone that had been squared off mostly. Where it was irregular, it appeared more that this was due to errosion of some kind. One could imagine it being /quite/ square. What the men would describe as "Unnatural"[fn:: This had a distinctly positive connotation. It had the sense of 'made by skilled cavepeople for utility and comfort.'].

The joints between the stones gave the impression that the creators had balanced finding an appropriately-shaped stone with the trouble of removing material to create a finer fit. The joints between the stones did not make a regular, gemoetric pattern like one would see in modern block construction. The lines between the stones were more jagged and irregular, but in a pleasing way. In this case, though, where there were joins, there were impossibly tight. There was the look of crazed lines scratched all over a smooth rock wall, for the exterior of the hide had proper "walls", at right angles to one another. It was made from irregularar stone puzzle pieces that somehow fit one another perfectly.

As the front of the hide came into view, they could see that some rather sophisticated modern construction had been done too: There was a sort of wood entrance-way constructed around the opening. The stone was clearly many rotting-ages of wood. The wood was comparatively new.

It was not a particularly inviting entrance. This structure was solely for the purpose of protecting the occupants.

There was a low, two man long sort of arched hallway made from woven and somewhat living vine. The walls of this tunnel were lined with dozens of sharpened, springy saplings all anchored at their base to the wall, hanging at lazy angles near the wall and all pointing outward.

It is a contrivance that the men were familiar with. Something like this was used sometimes to protect the opening of a cave from anything big enough to be a threat to humans.

Looking inward, one's eyes were met with a bunch of fire-hardened spikes making entrance impossible for a crazed, hungry predator but still allowing a human to patiently move spikes out of the way, using arms and legs to retain the ones you're already past, going slow and patiently. A human could get in with some strategy and patience. Nothing dumber could make it through, generally.

This was referred to in standard Crec as a spike-guard. It was known to Grav and Gog as a "porcupine-pussy"[fn:: They thought this much more descriptive and poetic.].

The Crec had latches and vine catches that would make ingress much easier than it was in this case, where they were both struggling, helping one another with a stab here or a smack there (from a poorly timed release of a branch bent out of the way). The baby gave them exasperated but patient looks as it stopped every pinkie-thumb or so to press back some of the troublesome spikes at their base and wait for the two enormous people to ease past all the many pain points.

The idea was obvious. This was a hide that the forest-child somehow knew about. The plains were not an option this evening, as the forest-child's message was ultimately pretty clear: There was a lizard-bird, hunting at night, which was the usual, and along the nearby plains[fn:: Which was also usual for a lizard-bird, though they were so rare as daily experiences go they hadn't really anticipated this particular problem, really. Caveman Thag would have been disappointed.].

And the hide was a perfect solution. They would likely just enjoy a night of periodic but contained terror as they get sniffed out and then mercilessly charged by an animal that gets bloodier and angrier with every failure. All three having spears, they would also get the pleasure of mortally wounding a tooth-cat or two with a satisfying stab down its throat[fn:: Tooth-cats were /hated/ among the Crec. Tooth-cats were for them what wolves are for settler sheep farmers. There was a mindless hatred. They would see no downside to all-out extension. Every Crec was at most two relations away from someone who had been killed and eaten by a pride of tooth-cat.].

For them it was a kind of entertainment.

The worst part of the night, they both knew, was going to be sharing a small burrow with a reeking baby who also happened to be a /very/ poor conversationalist.

Having gotten snugly into their hide-burrow and it now being properly dark, as best they could tell in the dark wood, Grav and Gog talked at length about their perdicament and plans.

For one, they would have to awake and get running dangerously early in order too beat conch. They would get docked by xxx for not having shaved[fn:: xx] and not wearing their rhino-calf chest armor[fn:: xxx].

The last palm of woods would not be entirely quiet at that time. Missing conch was punishable[fn:: xxx] and they were balancing the penalty for that with the reckoned odds of getting eaten by one thing or another along the way.

It was not unusual for a lizard-bird to continue its hunt until early morning, even after dawn. The men did have clear skies and enough moon going for them.

xxx
xxx they fight off animals
xxx one gets its claws in and tries to tear away the whole "tunnel" structure.
xxx they remark repeatedly about the stink.
xxx maybe the baby has a peace pipe?
xxx   - "we should take it easy. remember last time."
xxx   - baby smokes a shitload
xxx   - maybe they smoke, the men get paralyzed with "visions", baby
xxx     fights off everything by himself. (useless big people)
xxx they "wake up" get ready to, have a tearful goodbye with their
xxx new babyfriend.
xxx
xxx they cross the plains, maybe swat off a lizard-bird.
xxx They pass Verk's palace, remark or something.
xxx
xxx They get there. Find some musty, dusty armor to throw on, ill fitting.
xxx
xxx They /just make it/ to conch, stand at attention
xxx

--

Off the trails and off the plains meant /in the woods/ adjacent to Snare Plains, a place where rich biome met rich biome and all kinds of killing went on. It was, in literal terms, "between the plains and the woods"[fn:: Which of course is the Crec expression that means 'between a rock and a hard place'. 'The plains' being haunted by something like a lizard-bird in the metaphor.] This was a phrase that was bandied about, but it was no joke to be in there any more than is, say to be caught in /the undertow/.

And yet there they were. The forest-child was in-the-know about such things. There was no doubt. Lizard-bird aren't /everywhere/ in Crec. Given plenty of other factors, it took several hundred square miles to support just one. So they are rare, territorial, and deadly deadly. You might think in terms of the lizard-bird being to the Crec what great white shark is to modern humans, supposing of course that modern humans spend all their time swimming at the beach. These sky-trolling sharks were a lot less hypothetical, in other words; a lot more day-to-day. You were always right on the sky's shore, after all.
