#+title: Bivvy
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../index.css" />
#+OPTIONS: num:nil

[xxx] fully /after/ the Mr. Thag stuff. And....action!

Grav and Gog were faced with spending the night, baring a miracle, in the most dangerous place possible, only because a much greater danger had recently moved into the area, like bad weather, but worse.

This was part of the life-long education the Men had about lizard-birds.  The woods were safe, and yet they weren't. They were also the only reasonable choice. This was definitely toward the end of the curriculum, but they both knew the approximate odds of either choice, and chose the least bad.

Off the trails and off the plains meant /in the woods/ adjacent to Snare Plains, a place where rich biome met rich biome and all kinds of killing went on. It was, in literal terms, "between the plains and the woods"[fn:: Which of course is the Crec expression that means 'between a rock and a hard place'. 'The plains' being haunted by something like a lizard-bird in the metaphor.] This was a phrase that was bandied about, but it was no joke to be in there any more than is, say to be caught in /the undertow/.

And yet there they were. The forest-child was in-the-know about such things. There was no doubt. Lizard-bird aren't /everywhere/ in Crec. Given plenty of other factors, it took several hundred square miles to support just one. So they are rare, territorial, and deadly deadly. You might think in terms of the lizard-bird being to the Crec what great white shark is to modern humans, supposing of course that modern humans spend all their time swimming at the beach. These sky-trolling sharks were a lot less hypothetical, in other words; a lot more day-to-day. You were always right on the sky's shore, after all.
