#+title: Club-Drill
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../index.css" />
#+OPTIONS: num:nil

Club-drill was excruciating to the Grav and Gog in ways that they couldn't manage to communicate to others. It was mostly about being told what to do and being criticized by the ignorant and linear thinkers that were inevitably the "top bronze"; often criticized for doing exactly what you were told to do.

Another concept they wouldn't be able to explain or even be aware exists was "selection bias". It's a subtle idea. It would be a while before that idea got identified and tagged.

In words that a Crec might understand: The cavemen who made their way to the top in the hierarchy were the type who really liked bossing people about. They were cavemen who were violently uninterested in the wisdom of their plans for /you/.

Given enough cavemen, you will find some outliers. You may not know anyone who likes to give orders, doesn't like to be questioned, and doesn't care whether they are "right" by /your/ definition, but how many CO's[fn:: Caveman Officer] does one need? Not many. And being the scrappy sort, they will, in stages, work their way toward their dream job. Everyone should. Recruiting was no small part of the Armed-Forest. Outreach, recruitment and other kinds of advertising paid off in their growth, and in the recruitment of many particular /types/ to fill corresponding /roles/.

As a Crec, you could and probably would some day be drafted. But to make a career out of it was a different tack. If drafted and not a CO, you pretty much spent all your time either killing, being killed, or learning to kill. CO's were more the managerial type.

And so, since your fate, if a man, was to be involved in all this anyway, /completely voluntary/ "club-drills" were regularly held in locations around the Forest. If bloody combat was going to inevitably happen, one may as well be among the best-prepared.

You may have stopped and wondered yourself: What was it like to be among a sea of men on opposing "teams", all literally in a life-or-death fight with both sharp and blunt weapons of war, /right there in front of you/, wanting to kill you. And you wanting to kill because of that. It's an unimaginably frightening thought when it's both real and likely. Try and touch that kind of terror in yourself, see if you can imagine yourself in that terrifying bloody mess: This is what motivated Grav and Gog to trek all this way, all-too-regularly.

The clubbing-camps were usually overseen by some Great Bear war hero. The one nearest Bhorv Zolk, called Choh-Ov, was surrounded by a kind of suburb named Fayt-Caves, and was run by Verk. The title of this role, the camp head, was Mother Bear[fn:: Absolutely no one saw a hint of humor or absurdity in this title. Yes, it was well known that mother bears are female, but mother bears were and are fierce as monkey-business.]. Verk was Choh-Ov's Mother Bear.

Fayt-Caves was a shanty town, but made out of rock, which really looks nicer than shanty any way you cut it. The settlement surrounding Choh-Ov was seedy, crime-ridden, full of loud parties on an ongoing basis, had an entire district devoted to hire-baby-makers and their trade. Choh-Ov was more or less the yolk of this sad, desperate fried egg.

And it was small-knowledge[fn:: 'small[-one]-knowledge': common sense, widely known.] that this was the norm; surrounding more or less every clubbing-camp in the Forest and its protectorates was a 'bad neighborhood' by most definitions. No one thought this amiss. It was never questioned[fn:: This effect was also seen surrounding Crec's very few places of high learning, 'scratching-camps'].

Grav and Gog had decided to leave the day after the revelation of Ender's-Sword, giving them the opportunity to take make a leisurely day of it, needing only to cover one and one half of one all-finger palm[fn:: About 30 'imperial' miles.] of pretty standard jungle, woods, and scrubby savanna. with the way well-traveled and therefore clearly marked, well serviced by vendors, and safe-with-many. They had even let themselves sleep in a bit[fn:: With rare exception, all cavepeople woke at dawn, even on deeply overcast days. Another palm of sleep more, if you found a place dark enough, was considered decadent.]. Since the final part of the journey crossed a wide, flat, scrubby plane and the moon was sufficiently bright, they would be able to travel for hours after dark set in.

In the worst case, they planned to bevvy one night, wake up early and arrive at the Choh-Ov before conch.

As Bhorv Zolk faded into the distance, the path to the morning-sun-left-back-side[fn:: Northwest.] was gently rolling hills and low shrubs for several palm. Bhorv Zolk could be seen fading into the distance, which was a nice way to say goodbye to home. One got a feeling that it was very big, being visible from all this way, and would therefore surely be there when you got back[fn:: And coming back was also a nice, slow 'hello'. You felt 'home' many palm before you actually were.].

Gog hummed, whistled and yipped an improvised song, that Grav didn't really want to admit was actually pretty good.

He'd worked on convincing Gog to have a visit with Kapitle, the music-scratcher nearest Bhorv Zolk. Business was good and all number of copy-protection[fn:: explain!!] schemes were the key to success, Kapitle knew[fn:: But would not share.] He had a regular rotation of all-finger-and throat-and-drum-choirs that would snare[fn:: As in the impromptu bush trap. Their word for "kill at" or "really make a killing".] his most profitable demographic: all-finger-and boys trying to woo their crush by performing some music or other, using /his/ scratching standards and training system.

Sell the materials needed to perform a cover of the latest hit was really all there was in the music business, outside of performing of course, for which you would need security and acoustical expertise.

Grav just enjoyed the well selected traveling music and thought a lot about how to best navigate the next few days, not for any particular reason other than one should always plan ahead.

Would word have gotten out? Verk would not be at the camp, not feeling any particular need to be there. He would make his way back eventually, at his own pace, likely after Grav and Gog had gone <-xxx maybe they meet up on the way home xxx

A few palm outside of Fayt-Caves, Verk owned what would be considered a castle almost universally; a point that the men would pass late that evening, if they kept their pace.

"Would word of the Ender's-Sword have made it to Choh-Ov?", Grav wondered allowed.

Without breaking his stride, Gog abruptly stopped his music and looked at Grav, possibly thinking, or possibly for superb comedic timing.

"You mean Ender's-Stump?"

Grav's run became a staggering, rhythmic stomp as he laughed maniacally while continuing to run. He eventually gave up on that and let himself fall into an enormous healthy, dark-purple heather shrub. He continued to laugh face-down at the dirt and detritus at the ancient shrub's base. He noticed a worm quickly escaping downwards in his haze of mirth.

He eventually righted himself, making a lot of noise as he pushed himself up, snapping small branches and spitting out a sparse cloud of tiny purple petal glitter and twigs that had ended up in his open mouth.

"Scout[fn:: "Dude!!"], you need to lay off of that stuff! Not everyone is as mirth-filled as us, you know. The Forest Executioners are not known for their stoatishness[fn:: Sillyness].", said Grav.

"Eegh. I'm tired of worrying about it, to be frank." Gog was such an artist with his banana-language that he was no longer entertained by it, and so was laughing not at all. It seemed like he just thought of it as his 'job'; trudging through another day of saying things that caused others to nearly have a stroke with hilarity. "You know either of us could be dead tomorrow."

"Yeah, but probably not 'from torture'.", reasoned Gog.

"I mean, yeah, of course I will always take reasonable precautions. But mount it, it becomes so much of a drain on me to constantly have to edit my words that I'm willing to be a bit 'strategically reckless' in order to just relax for a /sewing/ change!!" Gog seemed to be shaking his head in disgust. "Also, I always feel like living another day so that I can say as much banana as I want is its own motivation to not get cheeped on[fn:: 'Snitched on', 'told on'. It was the the automonopoetic word for the sounds a baby bird makes, like in many langues, 'cheep'. So to 'cheap' on someone was to cry to mamma bird, in essence.]."

"They /are/ just words, aren't they?", said Grav, sharing some of Gog's annoyance at the arbitrariness of it all. Though, he was not yet an angry rebel like Gog. "It angers me too. Some things are at the same time both infuriatingly stupid and unjust, while at the same time being completely small-knowledge to seemingly everyone. Everyone gets so clubby[fn:: 'On edge'.] about /language/."

Grav continued. "Did you know that in Douks you can have three toenails pulled out for underpaying your take-value? Regardless of circumstances? At least the Crec haven't gone that crazy.

If you find something in the jungle of any value at all, the Douks Forest has a 'claim' on half of it, without any kind of justification. It's just /theirs/ and that's that!

How would you take-value half of one Ender's-Stump?"

Gog's cheeks tightened with the suppression of a smile.

"What has that got to do with what we're talking about?", asked Gog.

"Force is force <-xxx do we like 'force'? xxx, whether it's about taking value or removing freedom.

In a way, they're similar things; freedom and value. You can use your freedom to get value. Taking away your freedom is like taking value you don't yet have, because 'they' have wrecked your plans. Maybe /you/ want to be a professional banana-talker...!"

Gog answered with a question, while smirking gratefully. "Are we really gonna trek it out the whole way through, without a bevy?"

"Why not? So long as we hit Snare Plains by maybe one palm after sundown, we'll be set like a murderous monkey[fn:: A strange expression that means something like 'in like Flynn'. It comes from the observation that a monkey that has killed one of is own kind and is relaxing in its nest eating the corpse has a look of complete contentment, sometimes even with a bloody smile that humans easily pick up on.]."

"That's a palm of walking in the dark in Small Woods."

"Running.", corrected Grav.

Much later, it getting dark and their nearing the end of Small Woods, they encountered a forest-child[fn:: make sure naming is consistent and that there has been a footnote already.] whose path was intersecting with the only established trail for palm, as seems always to be the case, and only in the Forest; /any/ Forest.

"Greetings cheerful fellow traveler!", said Grav, there never having been any sense of fear about them from anyone that he could recall.

Grav knew he would not be able to make anything of the response. Each time, it seemed they had to rebuild the pantomime vocabulary with them from scratch. But they were practiced.

The forest-child <-xxx /was/ a child. It was astonishing. No matter how hard anyone had tried, they couldn't make out any dwarfish features. Other than often being scared and every so often missing fingers, teeth, eyes, or limbs, and but for heaving leathery, tough skin, they were what we moderns would call "toddlers".

They did not speak Crecspeak or anything remotely like it, but were evidently fluent in some kind of language. The small boy[fn:: No one had ever seen a female, and it was always apparent the present company was male in gender.] slouched in a way that a very relaxed, fit, successful older caveman would; a standing slouch that said he could take them or leave them. Or possibly even kill them. But he showed no sense of fear or hatred, just casual toddlerness. They smoked a pipe about half the time. This one was not a partaker[fn:: The ones that smoked, really smoked, and reeked of whatever weed they smoke.].

From appearances, the toddler had not yet considered that the two men might not understand his language. He paused very briefly on occasion in a way that suggested he was baffled by the lack of a response, but continued on just the same.

After an especially baffling non-response, Grav took the initiative to blow away his new friend with casual, pithy, fluently spoken Crec utterances; asking all kinds of questions about who cleaned him after scat time, where was this crazy toddler kingdom located, did he live in a mushroom, and aside from one's thumb, what kind of things were out there to suck on for an active baby like himself.

The light of understanding, forgiveness, and kindness to new friends dawned on the toddler's honest face. He bowed slightly, showing who-knows-what to the woods behind him.

He made a lot of "we friends" gestures with his hands, his heart, and his toothless smile. Grav and Gog mimicked the ones they felt pretty sure about.

Grav turned to Gog. "How is your forest-child-babble?"

Gog said, "More importantly what do we want to ask him. He's full of helpful answers, all written in High Ancient Balrag. What can we get out of him—then maybe see if he jumps for joy at a polished uvula."

Grav looked at the sky through the canopy and thought for a considerable while.

"Ok. Translator, ask him if he would chance the remainder of the xxx woods at a leisurely walk on the way to xxx plains, or would he run like scat?", Grav said to Gog.

"Oh. Thanks for starting with an easy one."

"Don't you think that'd be handy to know?"

"If we were that worried, we'd be running right now."

While the men were talking, the forest-child made a series of gestures. Warning and "no" could be seen on his countenance as he made his interpretive dance.

"Flying?", Gog thought picked up.

"Mouth? Beak?", Grav tried to help, in this elite level version of Pictionary, where the audience more or less mute; and dumb, from the forest-child's perspective.

"Is that a tail? Egg?"

"Lizard bird?", asked Grav.

His feedback from the toddler was a shrug.

"I'm pretty sure he is saying lizard-bird something. Egg...could it be eating for two and therefore especially hungry?"

Lizard-bird could and would kill men. There was no scooping up in the peak and swallowing whole. No, that would be better.

A rare survivor once enthusiastically gave his tale, to the best he could, without embellishment, just for the good of the Forest. He had a kind of speaking tour. /Stay Low to Scrub/ and its rejoinder shouted by his audience, /Stay Low to Mud/ were to catch phrases by which he was known. In other words: Hide, get out of the way [of the stalking lizard-bird]!

He would tour any demographic that would benefit, which would most of all be children. They would gather around him as he stood center stage, or whatever served in its place.

He would scare kids straight about lizard-bird awareness.

#+begin_somethen
Kids, as you know, my name is Thagalonious Son of Reginald, but you kids know me as Caveman Thag!

And I am so happy to be here. I want to tell you kids about how to be safe, and what to look out for when being lizard-bird-aware!
#+end_somethen

The kids shout aimlessly but with enthusiasm.

#+begin_quote
Many of you know some of my story, but I'm going to lay it out right here, like a slain lizard-bird, so you can learn from me. Okaay!?
#+end_quote

The kids shout again, and Thag points to the ground with his only arm on which there are really only two /sorts/ of fingers.

#+begin_quote
I say 'Stay Low to Scrub', and /you/ say...
#+end_quote

"**Stay! Low! to! Mud!**"

Thag smiled.

xxx xxx walk? doesn't everybody run? maybe there is the message of
xxx xxx "run, don't walk!" Lots of self-shaming for having been walking

#+begin_quote
/Well/... I was walk home from xxx along the path that many of you know well, it's not close to here, but it's close enough. Many of you have seen it in person. It was at Hummingbird Pass, which connects xxx and xxx, down at the far south of our Forest.

We have Balrag for neighbors, so we know a lot about getting along and also about surviving. They're good cavepeople.
#+end_quote

The children did not yet know that they should sneer at this.

#+begin_quote
I was minding my own business. I was on my third night, about half way through, as I had to go all the way from xxx to xxx to xxxtaskxxx.

It was not especially bright, as there was only a sliver of moon. The stars where bright where they shone, but there were as much cloudy sky as not, lots of burrows of sky for a big, mean bird to stay out of view; say, just until the last momement...
#+end_quote

The children said little but some seemed to be crawling backward using their arms as they sat on the floor.

#+begin_quote
I knew that a lizard-bird included this bit of path in its territory. And, remember this, in a woods thick enough to block the sky, a lizard-bird is always scanning the openings. In the case of us silly Crec that make nice, straight paths, a bird might choose to fly along a nice, straight course scanning for snacks. You my little ones, are snacked sized.
#+end_quote

A quite-one stepped all over the nighbors beihind her, faces, groins, wherever, in order to escape. Her brother, having been priming her with fear for days and knowing how to trigger her manic flight, just exactly.

Most boys laughed. Otherwise there was not much of a ruckus this scare around.

#+begin_quote
It was known then, and it is known still that these are the most hazardous. As cloud cover can give you a false set of ease, I was quite at ease, and walking in the middle of the path. I would only very rarely think about danger, walk to the side under the canopy, or turn my head in case I'm both very unlucky and lucky.
#+end_quote

Thag made a practiced, convincing lizard-bird screech[fn:: One absolutely never used by the bird itself while on the hunt, when it was as silent as a massive owl might be.].

As was always the case with large, temperamental crowds of human children, some added to the known scat-zones, crawling away unembarrassed. The loud, stunning screech was a crowd-pleaser, as the scat-er was immediately giggling and dancing soon enough. And children were hopeless in communicating the nuances of this, far from warning their friends in other parts. So this was always a genuine surprise and That loved it.

#+begin_quote
But I was not usually so careful, so then it came, eventually. I am unable to puzzle together anything, as I was walking in my own little world, at night in the woods; an older all-finger-and boy who could kick some ham, but was no match to a lizard-bird.
#+end_quote

Thag always had legitimate lament he could tap into at any time to bring the mood of the house back down to "somber". It was actually something that could be "tapped" in kind of the same way a keg of champagne can be: carefully sometimes sometimes disastrously. You got a lot more champagne than you anticipated.

Thag was quite afraid of lizard-bird still.

This time too, Thag had to snap out of it and continue his outreach. In the most productive way possible.

#+begin_quote
I was tackled from behind by what felt like being stabbed from behind by seven or eight blut but sharp obsidian blades and a massive speeding boulder of warmth, muiscles, and sparse, downy feathers.

He rode me like a hill-sled for probably four man. Talons squeezing as we slid. By the time we stopped. I felt like I had been wrapped in obsidian-vine[fn:: A vine that grows throughout the Crec realm. If carefully removed and uncoiled (which was obviously a dangerous art) from its host trees, which may be many, and then lightly fire-hardened. It could become a kind of barbed wire. But with pinkie-thumb sized, needle-pointed barbs.], with someone wrapping it ever-tighter. You don't know what it feels like to be mercilessly /squeezed/ by something so terrible...
#+end_quote

Thag trailed off, eyes empty. The children continued to watch until he shook himself and continued.

#+begin_quote
It was standing on top of me. And it was /heavey/. It was at least a good sized hyena's weight. As I struggled in a way only one in that situation can truly struggle, it would lift me about a palm with its wings, and then /slam/ me against the ground with all of its weight, making the talons as secure as possible in /me/.
#+end_quote

The speaker paused only briefly this time.

#+begin_quote
Once it was sure it had a good hold of me, I guess it wanted to make sure I was as dead as possible so I wouldn't be much trouble on the flight home, wherever that was. To this end he pecked me in the head repeatedly. I turned my head so he would be unable to peck the same place twice, if possible, and twisted all around to try and keep the blows from landing as much as possible.

And indeed that's where the first gap in my memory lives, although I'm able to fill it with all kinds of nightmares, and sometimes do. Don't lament small game[fn:: Don't sweat the small stuff. Don't cry over spilled milk.], kids.

When I came too, it was because he was slowing his flight to set me on his perch. It was a scat and bone covered fortress of sorts. It was clear that she[fn:: The male lizard-bird are xxx.] and she alone lived there. It was literally in the clouds so I only had the slightest idea, at least initially, of where I was and what was going on any more than all-finger man away.

I would soon find out. He started eating me at this point.
#+end_quote

The children's only reaction to this was to stare.

#+begin_quote
Birds naturally go after the softer parts. And since all of my might was tied up in protecting my eyes[fn:: Thag was missing both and had a retaneu of assistance for all of life's chores.], he had mostly free reign over my groin parts.
#+end_quote

The children didn't move, especially the boys.

#+begin_quote
I switched from protecting my eyes to protecting my groin as fast as I was able, but the bird had every possible advantage over me.

He took up /all/ of my parts, and then some, squeezed with his mighty beak and pulled. Of course he had flipped me over at this point and was putting new holes in my front half.

For him it truly was effortless. The shock and horror I was experiencing at the moment was a kind of protection for me. I don't know how the reflect-soul works, but I can recall no pain at all.

I just remember how effortlessly he tore off what to me was the most important part of my body at the time. It was like the meat had been scored deeply in advance. It just came right off and went down his thoat, her making a whole-body bob as he she tossed it down her own throat.

The wet sound of her feeding is something that stays with me. You don't think of what it might sound like. You don't get a chance to find out, unless you are unlucky-lucky[fn:: Crec used this compound to mean, 'Something terrible happened but something miraculous saved me.'] like me.

I could hear important parts of me going down her throat with a gulp.

The parts you see missing here are the parts she took.
#+end_quote

Thag took some time in reloushing another of his popular theatrics. He raised his one arm and blindly hopped in a circle, one of his thighs being about half as big around as the other. One ham mostly missing, and a dripping mess of leisurely, gravity-fed feces downward from where his anus used to be.

He completed his circle and made a smile, with the lower lip missing, which is a big smile indeed.

Some children giggled. Thag made an oddly raptor-like grabbing motion in the sound's direction as a friendly wave to a perfectly natural reaction from a child.

#+begin_quote
I had accepted that some time soon, I would fall asleep from all the blood loss and soon after die. It would be peaceful enough an end, I was unable to feel any pain at the time and felt like all this was happening to someone else.

Just then there was a "whoosh" like a cold wave of wind coming down a long, flat slope, along with a slight flash of gray over the whole rocky cliff side. I could tell it was something fast and enormous and of course I was right in guessing that it was another lizard-bird, snake-meal in the middle, wanting to steal a fresh, juicy, living prize away from its tormentor.

I knew it was just making a first pass. This could only improve my situation, but in my hopelessness I wasn't able to feel anything like hope.

That was the only exploritory pass it was to make. In the middle of my hazy awareness on this hazy mountain, I was suddenly flung, like a rock from a sling.

What I think had happened is this fast, competing bird had more or less tackled the one that was in the middle of eating me, causing it to tumble, where it released me on the up swing, mid-tumble.

I feel like I floated in the air for palm. When I finally landed, it was with a gentle "puff" rather than a jarring splat like I had expected, though not expected to notice.

I had landed in a man-deep, ancient bed of xxx moss that had been accumulating on that misty hillside probably for all-finger all-finger all-finger years.
#+end_quote

The children, knowing a thing or two about cave medicine, gave a tempered cheer, for they knew of the healing properties of xxx moss for just such injuries[fn:: Although Thag's surival was considered a miracle, as in this case, a third or more of the man's body had be eaten and the rest run through with talon repeatedly.].

#+begin_quote
No one, my self included could make any kind of meaningful guess as to how long I lay there. I of course was not there to count the suns.

I will say that when I finally got back, /before/ the many moons of rest with the tender care of my mother <-xxx, I had been gone for all-finger and seven days. The parts that I can remember probably only add up to a few <-xxx days.

I had to have been there, slowly recovering in that massive bed of moss for at least all-finger days, with no food, water or awareness.

I was just a hopeless husk of a caveman when I was able to, using only down-power and a lot of wiggling, start my descent, towards what or who, I had no idea. I was existing as a beetle exists. I was just mindlessly surviving.

At some point I was lucky enough to wiggle my way into a brook that I had heard getting nearer for many palm. I fell face first and immediately began to slurp. I slurped until I was full, and then slurped some more, I would sometimes throw up half, but start drinking right away again just the same, for blood comes from water and I had lost most.

xxx
#+end_quote



xxx Someone with a clever name scares kids straight about lizard bird awareness xxx



xxx 4 later: with hastily, poorly-appointed row after row of little hills, with a kind of crash pad of a cave.


